export interface WordEntry {
  /** The secret word the crew receives. */
  word: string;
  /** Vague single-word clues for the impostor — at least 3. One is shown at random each round. */
  hints: string[];
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  words: WordEntry[];
}

export const CATEGORIES: Category[] = [
  {
    id: "food",
    name: "Food & Drink",
    emoji: "🍕",
    words: [
      { word: "Pizza", hints: ["Delivery", "Slices", "Cheese", "Shareable"] },
      { word: "Sushi", hints: ["Chopsticks", "Cold", "Japanese", "Seaweed"] },
      { word: "Pancake", hints: ["Breakfast", "Stacked", "Syrup", "Griddle"] },
      { word: "Coffee", hints: ["Morning", "Caffeine", "Hot", "Mug"] },
      { word: "Ice cream", hints: ["Cold", "Flavors", "Melts", "Cone"] },
      { word: "Hamburger", hints: ["Fastfood", "Bun", "Handheld", "Fries"] },
      { word: "Spaghetti", hints: ["Italian", "Long", "Sauce", "Fork"] },
      { word: "Popcorn", hints: ["Movie", "Kernel", "Bucket", "Buttery"] },
      { word: "Chocolate", hints: ["Sweet", "Gift", "Melts", "Bar"] },
      { word: "Watermelon", hints: ["Summer", "Seeds", "Juicy", "Red"] },
      { word: "Tacos", hints: ["Handheld", "Spicy", "Shell", "Street"] },
      { word: "Ramen", hints: ["Noodles", "Japanese", "Bowl", "Egg"] },
      { word: "Donut", hints: ["Sweet", "Hole", "Glazed", "Dozen"] },
      { word: "Smoothie", hints: ["Blended", "Fruit", "Cold", "Healthy"] },
      { word: "Steak", hints: ["Grilled", "Meat", "Restaurant", "Knife"] },
      { word: "Salad", hints: ["Healthy", "Greens", "Side", "Dressing"] },
      { word: "Burrito", hints: ["Wrapped", "Large", "Beans", "Mexican"] },
      { word: "Waffles", hints: ["Breakfast", "Syrup", "Crispy", "Grid"] },
      { word: "Hot dog", hints: ["Street", "Bun", "Ballgame", "Condiments"] },
      { word: "Cheesecake", hints: ["Dessert", "Creamy", "Crust", "Rich"] },
      { word: "Milkshake", hints: ["Thick", "Cold", "Straw", "Blended"] },
      { word: "Fried rice", hints: ["Wok", "Rice", "Vegetables", "Takeout"] },
      { word: "Nachos", hints: ["Shareable", "Cheese", "Party", "Crunchy"] },
      { word: "Curry", hints: ["Spiced", "Rice", "Hot", "Aromatic"] },
      { word: "Bagel", hints: ["Round", "Toasted", "Hole", "Morning"] },
      { word: "Croissant", hints: ["Flaky", "French", "Buttery", "Breakfast"] },
      { word: "Lemonade", hints: ["Refreshing", "Tart", "Summer", "Citrus"] },
      { word: "Brownie", hints: ["Chocolate", "Fudgy", "Square", "Baked"] },
      { word: "Sushi roll", hints: ["Rolled", "Sliced", "Rice", "Fish"] },
      { word: "Pho", hints: ["Vietnamese", "Soup", "Noodles", "Broth"] },
      { word: "Mac and cheese", hints: ["Comfort", "Pasta", "Kids", "Creamy"] },
      { word: "Apple pie", hints: ["Dessert", "Warm", "Crust", "Tradition"] },
      { word: "Omelette", hints: ["Eggs", "Breakfast", "Filled", "Pan"] },
      { word: "French fries", hints: ["Salty", "Fried", "Ketchup", "Crispy"] },
      { word: "Soda", hints: ["Fizzy", "Can", "Sugary", "Ice"] },
      { word: "Pretzel", hints: ["Twisted", "Salty", "Fair", "Snack"] },
      { word: "Muffin", hints: ["Baked", "Flavors", "Blueberry", "Portion"] },
      { word: "Lasagna", hints: ["Layered", "Baked", "Pasta", "Crowd"] },
      { word: "Guacamole", hints: ["Dip", "Avocado", "Chips", "Party"] },
      { word: "Tea", hints: ["Hot", "Herbal", "Cup", "Worldwide"] },
      { word: "Cupcake", hints: ["Small", "Frosting", "Serving", "Birthday"] },
      { word: "Falafel", hints: ["Fried", "Pita", "Chickpeas", "Arabian"] },
      { word: "Paella", hints: ["Rice", "Spanish", "Seafood", "Pan"] },
      { word: "Cereal", hints: ["Breakfast", "Milk", "Box", "Crunchy"] },
      { word: "Dumplings", hints: ["Dough", "Steamed", "Filled", "Sauce"] },
      { word: "Popsicle", hints: ["Frozen", "Stick", "Fruity", "Melts"] },
      { word: "Chili", hints: ["Stew", "Spicy", "Beans", "Warming"] },
      { word: "Scone", hints: ["Pastry", "Tea", "Crumbly", "Baked"] },
      { word: "Bubble tea", hints: ["Trendy", "Pearls", "Sweet", "Straw"] },
      { word: "Pad thai", hints: ["Noodles", "Thai", "Savory", "Peanuts"] },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🦁",
    words: [
      { word: "Elephant", hints: ["Large", "Trunk", "Memory", "Ears"] },
      { word: "Penguin", hints: ["Cold", "Flightless", "Monochrome", "Waddles"] },
      { word: "Dolphin", hints: ["Water", "Intelligent", "Jumping", "Clicks"] },
      { word: "Kangaroo", hints: ["Jumps", "Pouch", "Australia", "Legs"] },
      { word: "Owl", hints: ["Nocturnal", "Head", "Predator", "Hoots"] },
      { word: "Snake", hints: ["Reptile", "Legless", "Venomous", "Slithers"] },
      { word: "Butterfly", hints: ["Flying", "Caterpillar", "Wings", "Flowers"] },
      { word: "Tiger", hints: ["Predator", "Stripes", "Cat", "Jungle"] },
      { word: "Rabbit", hints: ["Pet", "Ears", "Hops", "Carrots"] },
      { word: "Shark", hints: ["Dangerous", "Teeth", "Fin", "Ocean"] },
      { word: "Giraffe", hints: ["Neck", "Spotted", "Leaves", "Savanna"] },
      { word: "Panda", hints: ["Bear", "Bamboo", "China", "Cute"] },
      { word: "Wolf", hints: ["Canine", "Howls", "Pack", "Hunting"] },
      { word: "Horse", hints: ["Mammal", "Ride", "Mane", "Gallops"] },
      { word: "Eagle", hints: ["Predator", "Vision", "Strength", "Nest"] },
      { word: "Frog", hints: ["Water", "Jumps", "Tadpole", "Croaks"] },
      { word: "Bear", hints: ["Large", "Hibernates", "Dangerous", "Honey"] },
      { word: "Monkey", hints: ["Trees", "Agile", "Tail", "Fruit"] },
      { word: "Whale", hints: ["Largest", "Spout", "Sings", "Migrates"] },
      { word: "Fox", hints: ["Clever", "Tail", "Orange", "Dusk"] },
      { word: "Turtle", hints: ["Shell", "Slow", "Ancient", "Amphibious"] },
      { word: "Lion", hints: ["King", "Mane", "Pride", "Cat"] },
      { word: "Deer", hints: ["Antlers", "Forest", "Skittish", "Dawn"] },
      { word: "Octopus", hints: ["Ocean", "Arms", "Color", "Intelligent"] },
      { word: "Bee", hints: ["Honey", "Hive", "Sting", "Pollinates"] },
      { word: "Crocodile", hints: ["Reptile", "Water", "Jaws", "Ancient"] },
      { word: "Peacock", hints: ["Feathers", "Tail", "Bird", "Display"] },
      { word: "Hedgehog", hints: ["Spiky", "Ball", "Nocturnal", "Insects"] },
      { word: "Flamingo", hints: ["Balancing", "Pink", "Water", "Wading"] },
      { word: "Koala", hints: ["Trees", "Eucalyptus", "Australia", "Sleepy"] },
      { word: "Seal", hints: ["Cold", "Barks", "Flippers", "Sunbathe"] },
      { word: "Bat", hints: ["Flying", "Nocturnal", "Echolocation", "Inverted"] },
      { word: "Camel", hints: ["Humps", "Desert", "Water", "Transport"] },
      { word: "Parrot", hints: ["Colorful", "Mimics", "Tropical", "Beak"] },
      { word: "Jellyfish", hints: ["Ocean", "Boneless", "Sting", "Drifts"] },
      { word: "Squirrel", hints: ["Trees", "Nuts", "Tail", "Quick"] },
      { word: "Zebra", hints: ["Stripes", "Savanna", "Horse", "Herd"] },
      { word: "Hippo", hints: ["Large", "River", "Mouth", "Water"] },
      { word: "Chameleon", hints: ["Color", "Tongue", "Trees", "Slow"] },
      { word: "Otter", hints: ["Water", "Social", "Tools", "Sleek"] },
      { word: "Raccoon", hints: ["Masked", "Nocturnal", "Clever", "Trash"] },
      { word: "Pelican", hints: ["Coastal", "Pouch", "Fish", "Coast"] },
      { word: "Moose", hints: ["Deer", "Antlers", "Northern", "Tall"] },
      { word: "Crab", hints: ["Sideways", "Claws", "Shore", "Shell"] },
      { word: "Sloth", hints: ["Slow", "Trees", "Sleepy", "Claws"] },
      { word: "Platypus", hints: ["Eggs", "Bill", "Australia", "Unusual"] },
      { word: "Gorilla", hints: ["Ape", "Group", "Strong", "Herbivore"] },
      { word: "Lobster", hints: ["Ocean", "Claws", "Delicacy", "Red"] },
      { word: "Ant", hints: ["Small", "Colony", "Strong", "Teamwork"] },
      { word: "Peacock mantis shrimp", hints: ["Ocean", "Claws", "Colorful", "Punch"] },
    ],
  },
  {
    id: "places",
    name: "Places",
    emoji: "🌍",
    words: [
      { word: "Beach", hints: ["Relax", "Sand", "Water", "Sunbathe"] },
      { word: "Hospital", hints: ["Uniforms", "Sick", "Beds", "Doctors"] },
      { word: "Airport", hints: ["Travelers", "Security", "Waiting", "Planes"] },
      { word: "Library", hints: ["Quiet", "Books", "Borrow", "Silence"] },
      { word: "Stadium", hints: ["Crowds", "Seats", "Events", "Fans"] },
      { word: "Museum", hints: ["Learn", "Exhibits", "Display", "Tours"] },
      { word: "Restaurant", hints: ["Served", "Menu", "Eat", "Waiter"] },
      { word: "School", hints: ["Routine", "Classrooms", "Learn", "Students"] },
      { word: "Mountain", hints: ["Outdoors", "Tall", "Climb", "Snow"] },
      { word: "Cinema", hints: ["Entertainment", "Dark", "Screen", "Tickets"] },
      { word: "Park", hints: ["Green", "Benches", "Kids", "Picnic"] },
      { word: "Supermarket", hints: ["Groceries", "Aisles", "Public", "Checkout"] },
      { word: "Hotel", hints: ["Overnight", "Desk", "Beds", "Pool"] },
      { word: "Zoo", hints: ["Animals", "Families", "Enclosures", "Educational"] },
      { word: "Church", hints: ["Worship", "Glass", "Sunday", "Pews"] },
      { word: "Gym", hints: ["Exercise", "Weights", "Workout", "Membership"] },
      { word: "Amusement park", hints: ["Rides", "Lines", "Excitement", "Mascot"] },
      { word: "Post office", hints: ["Packages", "Government", "Stamps", "Queues"] },
      { word: "Bank", hints: ["Money", "Tellers", "ATM", "Security"] },
      { word: "Farm", hints: ["Crops", "Rural", "Mornings", "Tractors"] },
      { word: "Desert", hints: ["Dry", "Extreme", "Empty", "Sand"] },
      { word: "Island", hints: ["Water", "Tropical", "Isolated", "Vacation"] },
      { word: "Forest", hints: ["Trees", "Animals", "Dark", "Hiking"] },
      { word: "Subway station", hints: ["Underground", "Trains", "Rushing", "Turnstiles"] },
      { word: "Shopping mall", hints: ["Stores", "Shops", "Indoor", "Weekends"] },
      { word: "Aquarium", hints: ["Fish", "Educational", "Water", "Tanks"] },
      { word: "Castle", hints: ["Old", "Hill", "Tourist", "Stone"] },
      { word: "Campground", hints: ["Tents", "Outdoors", "Campfire", "Nature"] },
      { word: "Office", hints: ["Desks", "Meetings", "Business", "Weekdays"] },
      { word: "Harbor", hints: ["Boats", "Coast", "Sea", "Fishing"] },
      { word: "Observatory", hints: ["Stars", "Telescope", "Hilltop", "Night"] },
      { word: "Prison", hints: ["Held", "Walls", "Secure", "Visits"] },
      { word: "Cemetery", hints: ["Quiet", "Headstones", "Remember", "Flowers"] },
      { word: "Marketplace", hints: ["Vendors", "Outdoors", "Bustling", "Produce"] },
      { word: "Volcano", hints: ["Erupts", "Hot", "Cone", "Lava"] },
      { word: "Waterfall", hints: ["Falling", "Nature", "Loud", "Mist"] },
      { word: "Lighthouse", hints: ["Guides", "Coast", "Beam", "Tall"] },
      { word: "Cave", hints: ["Underground", "Dark", "Stalactites", "Explorers"] },
      { word: "University", hints: ["Education", "Lectures", "Students", "Sprawling"] },
      { word: "Bakery", hints: ["Aroma", "Bread", "Pastries", "Early"] },
      { word: "Nightclub", hints: ["Music", "Late", "Dancing", "Bar"] },
      { word: "Gas station", hints: ["Fuel", "Convenience", "Roadside", "Pumps"] },
      { word: "Courthouse", hints: ["Law", "Judges", "Trials", "Formal"] },
      { word: "Playground", hints: ["Kids", "Slides", "Recreation", "School"] },
      { word: "Spa", hints: ["Relax", "Massage", "Calm", "Unwind"] },
      { word: "Train station", hints: ["Trains", "Platforms", "Tickets", "Announcements"] },
      { word: "Rooftop", hints: ["Top", "Views", "Garden", "Windy"] },
      { word: "Warehouse", hints: ["Storage", "Industrial", "Forklifts", "Crates"] },
      { word: "Botanical garden", hints: ["Plants", "Peaceful", "Labels", "Photos"] },
      { word: "Skatepark", hints: ["Ramps", "Youth", "Wheels", "Outdoor"] },
    ],
  },
  {
    id: "objects",
    name: "Everyday Objects",
    emoji: "📦",
    words: [
      { word: "Umbrella", hints: ["Weather", "Dry", "Opens", "Handle"] },
      { word: "Toothbrush", hints: ["Daily", "Bathroom", "Bristles", "Clean"] },
      { word: "Mirror", hints: ["Home", "Look", "Glass", "Reflects"] },
      { word: "Backpack", hints: ["Carry", "Straps", "Holds", "Back"] },
      { word: "Candle", hints: ["Light", "Wick", "Melts", "Atmosphere"] },
      { word: "Clock", hints: ["Time", "Hands", "Wall", "Tracks"] },
      { word: "Pillow", hints: ["Bedroom", "Soft", "Head", "Bed"] },
      { word: "Scissors", hints: ["Tool", "Blades", "Cutting", "Desk"] },
      { word: "Wallet", hints: ["Safe", "Pocket", "Cards", "Leather"] },
      { word: "Key", hints: ["Opens", "Metal", "Lock", "Keychain"] },
      { word: "Phone", hints: ["Pocket", "Daily", "Screen", "Calls"] },
      { word: "Laptop", hints: ["Portable", "Keyboard", "Foldable", "Work"] },
      { word: "Headphones", hints: ["Ears", "Audio", "Cord", "Commute"] },
      { word: "Pen", hints: ["Writing", "Ink", "Pocket", "Empties"] },
      { word: "Notebook", hints: ["Pages", "Notes", "Bag", "Lines"] },
      { word: "Bottle", hints: ["Liquids", "Cap", "Reusable", "Plastic"] },
      { word: "Chair", hints: ["Sit", "Legs", "Everywhere", "Styles"] },
      { word: "Lamp", hints: ["Light", "Plug", "Desk", "Shade"] },
      { word: "Towel", hints: ["Bathing", "Absorbs", "Hung", "Soft"] },
      { word: "Remote control", hints: ["Channels", "Buttons", "Couch", "Batteries"] },
      { word: "Sunglasses", hints: ["Face", "Bright", "Lenses", "Summer"] },
      { word: "Watch", hints: ["Wrist", "Time", "Strap", "Smart"] },
      { word: "Comb", hints: ["Hair", "Teeth", "Bathroom", "Portable"] },
      { word: "Flashlight", hints: ["Light", "Batteries", "Handheld", "Emergency"] },
      { word: "Hammer", hints: ["Tool", "Handle", "Toolbox", "Nails"] },
      { word: "Plate", hints: ["Eat", "Round", "Kitchen", "Set"] },
      { word: "Spoon", hints: ["Eating", "Bowl", "Set", "Metal"] },
      { word: "Blanket", hints: ["Warm", "Bed", "Soft", "Snuggle"] },
      { word: "Shovel", hints: ["Digging", "Handle", "Blade", "Garden"] },
      { word: "Rope", hints: ["Tying", "Long", "Fibers", "Strong"] },
      { word: "Glue", hints: ["Sticks", "Tube", "Dries", "Crafts"] },
      { word: "Tape", hints: ["Sticky", "Sealing", "Roll", "Tears"] },
      { word: "Basket", hints: ["Carrying", "Handle", "Woven", "Picnic"] },
      { word: "Thermometer", hints: ["Temperature", "Sick", "Scale", "Mouth"] },
      { word: "Alarm clock", hints: ["Wakes", "Loud", "Nightstand", "Bedtime"] },
      { word: "Trash can", hints: ["Waste", "Lid", "Emptied", "Room"] },
      { word: "Hanger", hints: ["Clothes", "Shoulders", "Closet", "Plastic"] },
      { word: "Soap", hints: ["Cleaning", "Foamy", "Bathroom", "Bar"] },
      { word: "Bandage", hints: ["Wound", "Adhesive", "Firstaid", "Sticky"] },
      { word: "Extension cord", hints: ["Power", "Plugs", "Outdoor", "Trip"] },
      { word: "Stapler", hints: ["Papers", "Staples", "Desk", "Click"] },
      { word: "Calculator", hints: ["Math", "Buttons", "School", "Battery"] },
      { word: "Envelope", hints: ["Letter", "Sealed", "Mailed", "Paper"] },
      { word: "Paintbrush", hints: ["Painting", "Bristles", "Color", "Sizes"] },
      { word: "Ladder", hints: ["Reach", "Rungs", "Leans", "Dangerous"] },
      { word: "Fan", hints: ["Air", "Blades", "Cool", "Plug"] },
      { word: "Iron", hints: ["Wrinkles", "Hot", "Clothes", "Plate"] },
      { word: "Vacuum cleaner", hints: ["Floors", "Loud", "Hose", "Dust"] },
      { word: "Suitcase", hints: ["Travel", "Wheels", "Clothes", "Airport"] },
      { word: "Doorbell", hints: ["Rings", "Door", "Visitors", "Chime"] },
    ],
  },
  {
    id: "movies",
    name: "Movies & Shows",
    emoji: "🎬",
    words: [
      { word: "Titanic", hints: ["Romance", "Ship", "Ocean", "Disaster"] },
      { word: "Frozen", hints: ["Animated", "Song", "Ice", "Sisters"] },
      { word: "Harry Potter", hints: ["Books", "Magic", "School", "Scar"] },
      { word: "Star Wars", hints: ["Scifi", "Space", "Villain", "Lightsaber"] },
      { word: "Avengers", hints: ["Superhero", "Team", "Action", "Marvel"] },
      { word: "Jurassic Park", hints: ["Creatures", "Island", "Science", "Dinosaurs"] },
      { word: "The Lion King", hints: ["Animated", "Wild", "Animals", "Prince"] },
      { word: "Spider-Man", hints: ["Superhero", "Teenager", "Powers", "Swings"] },
      { word: "F.R.I.E.N.D.S.", hints: ["Sitcom", "City", "Group", "Coffeehouse"] },
      { word: "Squid Game", hints: ["Survival", "Games", "Stakes", "Korean"] },
      { word: "The Office", hints: ["Sitcom", "Documentary", "Company", "Boss"] },
      { word: "The Big Bang Theory", hints: ["Scientists", "Nerdy", "Apartment", "Knocking"] },
      { word: "The Simpsons", hints: ["Animated", "Yellow", "Decades", "Town"] },
      { word: "Breaking Bad", hints: ["Crime", "Teacher", "Desert", "Transformation"] },
      { word: "Game of Thrones", hints: ["Fantasy", "Kingdoms", "Dragons", "Books"] },
      { word: "Stranger Things", hints: ["Eighties", "Supernatural", "Kids", "Town"] },
      { word: "The Matrix", hints: ["Scifi", "Reality", "Coats", "Simulation"] },
      { word: "Inception", hints: ["Dreams", "Heist", "Nolan", "Top"] },
      { word: "Toy Story", hints: ["Animated", "Toys", "Pixar", "Cowboy"] },
      { word: "Finding Nemo", hints: ["Ocean", "Father", "Pixar", "Forgetful"] },
      { word: "Shrek", hints: ["Ogre", "Fairytale", "Swamp", "Donkey"] },
      { word: "The Godfather", hints: ["Crime", "Family", "America", "Offer"] },
      { word: "Forrest Gump", hints: ["Running", "History", "Chocolates", "Wise"] },
      { word: "Pulp Fiction", hints: ["Nonlinear", "Tarantino", "Storylines", "Dance"] },
      { word: "The Shawshank Redemption", hints: ["Prison", "Hope", "Sentence", "Escape"] },
      { word: "Jaws", hints: ["Thriller", "Underwater", "Beach", "Boat"] },
      { word: "E.T.", hints: ["Alien", "Boy", "Home", "Spielberg"] },
      { word: "Back to the Future", hints: ["Timetravel", "Car", "Decades", "Parents"] },
      { word: "The Hunger Games", hints: ["Dystopian", "Survival", "Broadcast", "District"] },
      { word: "Black Panther", hints: ["Superhero", "Africa", "Marvel", "Wakanda"] },
      { word: "Moana", hints: ["Animated", "Ocean", "Leader", "Disney"] },
      { word: "Coco", hints: ["Animated", "Family", "Music", "Pixar"] },
      { word: "The Walking Dead", hints: ["Apocalypse", "Undead", "Survival", "Series"] },
      { word: "Seinfeld", hints: ["Nothing", "Manhattan", "Friends", "Observational"] },
      { word: "How I Met Your Mother", hints: ["Flashback", "Manhattan", "Umbrella", "Romance"] },
      { word: "Brooklyn Nine-Nine", hints: ["Police", "Precinct", "Quotable", "Diverse"] },
      { word: "The Crown", hints: ["Royalty", "Historical", "Streaming", "Decades"] },
      { word: "Wednesday", hints: ["Dark", "Gothic", "Family", "Netflix"] },
      { word: "Avatar", hints: ["Planet", "Blue", "Pandora", "Cameron"] },
      { word: "Gladiator", hints: ["Rome", "Arena", "General", "Entertained"] },
      { word: "Interstellar", hints: ["Space", "Time", "Nolan", "Wormhole"] },
      { word: "La La Land", hints: ["Musical", "Hollywood", "Dreams", "Jazz"] },
      { word: "Parasite", hints: ["Korean", "Class", "Oscars", "Wealthy"] },
      { word: "The Mandalorian", hints: ["Western", "Universe", "Helmet", "Grogu"] },
      { word: "WandaVision", hints: ["Sitcom", "Reality", "Marvel", "Grief"] },
      { word: "Encanto", hints: ["Animated", "Family", "Disney", "House"] },
      { word: "Top Gun", hints: ["Pilots", "Aerial", "Volleyball", "Speed"] },
      { word: "Dune", hints: ["Desert", "Politics", "Chosen", "Sandworms"] },
      { word: "Oppenheimer", hints: ["Biographical", "Bomb", "Nolan", "Monochrome"] },
      { word: "Barbie", hints: ["Blockbuster", "Doll", "Pink", "Identity"] },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    emoji: "⚽",
    words: [
      { word: "Football", hints: ["Team", "Feet", "Goals", "Popular"] },
      { word: "Basketball", hints: ["Ball", "Hoop", "Jumping", "Court"] },
      { word: "Tennis", hints: ["Racket", "Net", "Singles", "Love"] },
      { word: "Swimming", hints: ["Water", "Olympic", "Strokes", "Lanes"] },
      { word: "Boxing", hints: ["Combat", "Gloves", "Ring", "Rounds"] },
      { word: "Golf", hints: ["Outdoor", "Clubs", "Hole", "Course"] },
      { word: "Cycling", hints: ["Vehicle", "Wheels", "Race", "Tour"] },
      { word: "Skiing", hints: ["Winter", "Snow", "Downhill", "Boards"] },
      { word: "Volleyball", hints: ["Net", "Hands", "Beach", "Six"] },
      { word: "Bowling", hints: ["Indoor", "Strike", "Roll", "Pins"] },
      { word: "Baseball", hints: ["Bat", "Innings", "Strikes", "Pastime"] },
      { word: "Cricket", hints: ["Bat", "Popular", "Days", "Wickets"] },
      { word: "Rugby", hints: ["Physical", "Oval", "Tackles", "Britain"] },
      { word: "Hockey", hints: ["Ice", "Stick", "Puck", "Physical"] },
      { word: "Badminton", hints: ["Racket", "Shuttlecock", "Net", "Reflexes"] },
      { word: "Table tennis", hints: ["Table", "Fast", "Pingpong", "Indoor"] },
      { word: "Archery", hints: ["Bow", "Target", "Steady", "Olympic"] },
      { word: "Fencing", hints: ["Sword", "Combat", "Gear", "Touch"] },
      { word: "Wrestling", hints: ["Grappling", "Pin", "Physical", "Ancient"] },
      { word: "Surfing", hints: ["Waves", "Board", "Balance", "Hawaii"] },
      { word: "Skateboarding", hints: ["Board", "Tricks", "Street", "Olympic"] },
      { word: "Gymnastics", hints: ["Flexibility", "Apparatus", "Form", "Flips"] },
      { word: "Marathon", hints: ["Long", "Miles", "Endurance", "Crowds"] },
      { word: "Triathlon", hints: ["Three", "Endurance", "Demanding", "Ironman"] },
      { word: "Diving", hints: ["Platform", "Form", "Splash", "Olympic"] },
      { word: "Rowing", hints: ["Water", "Oars", "Team", "Rhythm"] },
      { word: "Sailing", hints: ["Wind", "Water", "Sails", "Navigation"] },
      { word: "Rock climbing", hints: ["Vertical", "Ropes", "Outdoor", "Grip"] },
      { word: "Martial arts", hints: ["Combat", "Styles", "Belts", "Discipline"] },
      { word: "Lacrosse", hints: ["Stick", "Fast", "Native", "Field"] },
      { word: "Polo", hints: ["Horseback", "Mallet", "Team", "Wealth"] },
      { word: "Handball", hints: ["Hands", "Indoor", "Goal", "Europe"] },
      { word: "Squash", hints: ["Court", "Fast", "Players", "Racket"] },
      { word: "Billiards", hints: ["Felt", "Cue", "Pockets", "Pool"] },
      { word: "Darts", hints: ["Board", "Pub", "Bullseye", "Accuracy"] },
      { word: "Weightlifting", hints: ["Barbell", "Weight", "Olympic", "Strength"] },
      { word: "Figure skating", hints: ["Ice", "Routine", "Artistry", "Winter"] },
      { word: "Snowboarding", hints: ["Snow", "Board", "Tricks", "Slopes"] },
      { word: "Motorsport", hints: ["Vehicles", "Speed", "Track", "Formula"] },
      { word: "Equestrian", hints: ["Horses", "Rider", "Olympic", "Training"] },
      { word: "Curling", hints: ["Ice", "Stones", "Brooms", "Winter"] },
      { word: "Softball", hints: ["Baseball", "Ball", "Diamond", "Schools"] },
      { word: "Water polo", hints: ["Pool", "Team", "Goal", "Tiring"] },
      { word: "Parkour", hints: ["Obstacles", "Jumping", "Urban", "Agility"] },
      { word: "Ultimate frisbee", hints: ["Disc", "Team", "Noref", "Field"] },
      { word: "Kickboxing", hints: ["Striking", "Kicks", "Ring", "Cardio"] },
      { word: "Bobsled", hints: ["Track", "Sled", "Winter", "Fast"] },
      { word: "Biathlon", hints: ["Skiing", "Winter", "Rifle", "Scandinavia"] },
      { word: "Sumo", hints: ["Japanese", "Large", "Ring", "Push"] },
      { word: "Cheerleading", hints: ["Support", "Chants", "Games", "Coordination"] },
    ],
  },
  {
    id: "esports",
    name: "Esports",
    emoji: "🎮",
    words: [
      { word: "League of Legends", hints: ["MOBA", "Teams", "Champions", "Rift"] },
      { word: "Valorant", hints: ["Tactical", "Agents", "Defuse", "Riot"] },
      { word: "Fortnite", hints: ["Survival", "Building", "Lastman", "Dances"] },
      { word: "Overwatch", hints: ["Squad", "Heroes", "Objective", "Blizzard"] },
      { word: "Dota 2", hints: ["MOBA", "Prizepool", "Fives", "International"] },
      { word: "CS:GO", hints: ["Competitive", "Terrorists", "Buy", "Bomb"] },
      { word: "PUBG", hints: ["Survival", "Drop", "Zone", "Chicken"] },
      { word: "Apex Legends", hints: ["Survival", "Squads", "Legends", "Respawn"] },
      { word: "Rainbow Six Siege", hints: ["Tactical", "Defenders", "Destruction", "Operators"] },
      { word: "Call of Duty", hints: ["Shooter", "Series", "Campaign", "Warzone"] },
      { word: "FIFA", hints: ["Sports", "Football", "Yearly", "Cards"] },
      { word: "Minecraft", hints: ["Sandbox", "Blocks", "Building", "Creepers"] },
      { word: "Roblox", hints: ["Sandbox", "Platform", "Kids", "Community"] },
      { word: "Stumble Guys", hints: ["Party", "Racing", "Obstacles", "Beans"] },
      { word: "Rocket League", hints: ["Cars", "Boost", "Threes", "Competitive"] },
      { word: "Super Smash Bros", hints: ["Fighting", "Nintendo", "Stage", "Tournament"] },
      { word: "Street Fighter", hints: ["Fighting", "Hadouken", "Combat", "Combos"] },
      { word: "Tekken", hints: ["Fighting", "Inputs", "Series", "Dojo"] },
      { word: "Hearthstone", hints: ["Cards", "Blizzard", "Strategy", "Decks"] },
      { word: "StarCraft II", hints: ["Strategy", "Factions", "Korean", "Blizzard"] },
      { word: "Age of Empires", hints: ["Strategy", "Civilizations", "Historical", "Revived"] },
      { word: "Clash Royale", hints: ["Mobile", "Lanes", "Supercell", "Quick"] },
      { word: "Clash of Clans", hints: ["Mobile", "Raid", "Supercell", "Global"] },
      { word: "Among Us", hints: ["Deduction", "Impostor", "Spaceship", "Lockdown"] },
      { word: "Fall Guys", hints: ["Party", "Beans", "Obstacles", "Lastman"] },
      { word: "Genshin Impact", hints: ["Exploration", "Gacha", "Anime", "Elemental"] },
      { word: "Mobile Legends", hints: ["Mobile","MOBA", "Asia", "5v5", "Quick"] },
      { word: "Free Fire", hints: ["Mobile", "Brazil", "Fast", "Garena"] },
      { word: "Brawl Stars", hints: ["Mobile", "Threes", "Supercell", "Cartoon"] },
      { word: "Counter-Strike 2", hints: ["Tactical", "Bomb", "Skins", "Valve"] },
      { word: "Teamfight Tactics", hints: ["Autobattler", "Board", "League", "Strategy"] },
      { word: "Halo", hints: ["Scifi", "Spartan", "Xbox", "Multiplayer"] },
      { word: "Smite", hints: ["Moba", "Gods", "Hirez", "Camera"] },
      { word: "Paladins", hints: ["Heroes", "Similar", "Hirez", "Free"] },
      { word: "Warzone", hints: ["Survival", "Franchise", "Drop", "Gulag"] },
      { word: "Dead by Daylight", hints: ["Horror", "Killer", "Repair", "Licensed"] },
      { word: "League of Legends Wild Rift", hints: ["Mobile", "Shorter", "Riot", "Fives"] },
      { word: "Pokémon Unite", hints: ["Moba", "Creatures", "Tencent", "Goals"] },
      { word: "EA Sports FC", hints: ["Football", "Replaced", "Yearly", "Cards"] },
      { word: "NBA 2K", hints: ["Basketball", "Career", "Yearly", "Realistic"] },
      { word: "Gran Turismo", hints: ["Racing", "Console", "Cars", "Physics"] },
      { word: "F1 Esports", hints: ["Racing", "Drivers", "Official", "Simulation"] },
      { word: "osu!", hints: ["Rhythm", "Circles", "Skill", "Maps"] },
      { word: "Geometry Dash", hints: ["Rhythm", "Tapping", "Difficult", "Cube"] },
      { word: "Terraria", hints: ["Sandbox", "Dig", "Bosses", "Comparison"] },
      { word: "World of Warcraft", hints: ["Mmo", "Raids", "Blizzard", "Subscription"] },
      { word: "Final Fantasy XIV", hints: ["Mmorpg", "Acclaimed", "Japanese", "Community"] },
      { word: "Elden Ring", hints: ["Souls", "Exploration", "Fromsoftware", "Challenging"] },
      { word: "Splatoon", hints: ["Shooter", "Paint", "Nintendo", "Ink"] },
      { word: "Marvel Rivals", hints: ["Heroes", "Marvel", "Sixes", "Recent"] },
    ],
  },
];

export function randomWord(category: Category): WordEntry {
  return category.words[Math.floor(Math.random() * category.words.length)];
}

export function randomHint(entry: WordEntry): string {
  return entry.hints[Math.floor(Math.random() * entry.hints.length)];
}
