export interface WordEntry {
  /** The secret word the crew receives. */
  word: string;
  /** Vague, hard single-word clues for the impostor — at least 3. One is shown at random each round. */
  hints: string[];
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  words: WordEntry[];
}

export const CATEGORIES: Category[] = [
  {
    id: "food",
    name: "Food & Drink",
    emoji: "🍕",
    words: [
      { word: "Pizza", hints: ["Friday", "Box", "Sharing", "Oven"] },
      { word: "Sushi", hints: ["Raw", "Quiet", "Delicate", "Tray"] },
      { word: "Pancake", hints: ["Stack", "Weekend", "Flip", "Butter"] },
      { word: "Coffee", hints: ["Awake", "Bitter", "Steam", "Routine"] },
      { word: "Ice cream", hints: ["Drip", "Childhood", "Cone", "Brainfreeze"] },
      { word: "Hamburger", hints: ["Drive-thru", "Greasy", "Stack", "Napkin"] },
      { word: "Spaghetti", hints: ["Twirl", "Messy", "Long", "Sauce"] },
      { word: "Popcorn", hints: ["Crunch", "Dark", "Bucket", "Salt"] },
      { word: "Chocolate", hints: ["Gift", "Melt", "Craving", "Wrapper"] },
      { word: "Watermelon", hints: ["Picnic", "Spit", "Sticky", "Summer"] },
      { word: "Tacos", hints: ["Crunch", "Messy", "Fold", "Street"] },
      { word: "Ramen", hints: ["Slurp", "Steam", "Late", "Broth"] },
      { word: "Donut", hints: ["Hole", "Glaze", "Dozen", "Office"] },
      { word: "Smoothie", hints: ["Blend", "Straw", "Gym", "Purple"] },
      { word: "Steak", hints: ["Sizzle", "Rare", "Knife", "Date"] },
      { word: "Salad", hints: ["Crunch", "Guilt", "Bowl", "Dressing"] },
      { word: "Burrito", hints: ["Wrap", "Heavy", "Foil", "Messy"] },
      { word: "Waffles", hints: ["Grid", "Crisp", "Weekend", "Syrup"] },
      { word: "Hot dog", hints: ["Stadium", "Mustard", "Street", "Bun"] },
      { word: "Cheesecake", hints: ["Dense", "Slice", "Rich", "Cafe"] },
      { word: "Milkshake", hints: ["Thick", "Straw", "Diner", "Brainfreeze"] },
      { word: "Fried rice", hints: ["Leftover", "Wok", "Sizzle", "Takeout"] },
      { word: "Nachos", hints: ["Share", "Crunch", "Party", "Messy"] },
      { word: "Curry", hints: ["Aroma", "Rice", "Warm", "Spice"] },
      { word: "Bagel", hints: ["Hole", "Chewy", "Morning", "Toast"] },
      { word: "Croissant", hints: ["Flake", "Buttery", "Cafe", "Layers"] },
      { word: "Lemonade", hints: ["Tart", "Pitcher", "Porch", "Ice"] },
      { word: "Brownie", hints: ["Fudge", "Square", "Dense", "Bake"] },
      { word: "Sushi roll", hints: ["Slice", "Dip", "Tray", "Quiet"] },
      { word: "Pho", hints: ["Steam", "Slurp", "Herbs", "Bowl"] },
      { word: "Mac and cheese", hints: ["Comfort", "Kids", "Gooey", "Oven"] },
      { word: "Apple pie", hints: ["Warm", "Holiday", "Crust", "Home"] },
      { word: "Omelette", hints: ["Fold", "Morning", "Fill", "Pan"] },
      { word: "French fries", hints: ["Salt", "Side", "Crisp", "Dip"] },
      { word: "Soda", hints: ["Fizz", "Can", "Ice", "Burp"] },
      { word: "Pretzel", hints: ["Twist", "Salt", "Fair", "Chewy"] },
      { word: "Muffin", hints: ["Top", "Morning", "Paper", "Crumb"] },
      { word: "Lasagna", hints: ["Layers", "Heavy", "Oven", "Sunday"] },
      { word: "Guacamole", hints: ["Dip", "Green", "Party", "Mash"] },
      { word: "Tea", hints: ["Steam", "Calm", "Cup", "Afternoon"] },
      { word: "Cupcake", hints: ["Frosting", "Tiny", "Party", "Paper"] },
      { word: "Falafel", hints: ["Crisp", "Pocket", "Ball", "Street"] },
      { word: "Paella", hints: ["Pan", "Share", "Saffron", "Crowd"] },
      { word: "Cereal", hints: ["Bowl", "Morning", "Crunch", "Splash"] },
      { word: "Dumplings", hints: ["Steam", "Dip", "Bite", "Fold"] },
      { word: "Popsicle", hints: ["Stick", "Drip", "Summer", "Freeze"] },
      { word: "Chili", hints: ["Warm", "Bowl", "Kick", "Winter"] },
      { word: "Scone", hints: ["Crumb", "Afternoon", "Butter", "Dry"] },
      { word: "Bubble tea", hints: ["Chew", "Straw", "Trendy", "Sweet"] },
      { word: "Pad thai", hints: ["Tangy", "Wok", "Street", "Nuts"] },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🦁",
    words: [
      { word: "Elephant", hints: ["Memory", "Heavy", "Dust", "Gentle"] },
      { word: "Penguin", hints: ["Waddle", "Slide", "Tuxedo", "Huddle"] },
      { word: "Dolphin", hints: ["Click", "Leap", "Playful", "Smart"] },
      { word: "Kangaroo", hints: ["Bounce", "Pocket", "Punch", "Dust"] },
      { word: "Owl", hints: ["Twist", "Silent", "Night", "Stare"] },
      { word: "Snake", hints: ["Hiss", "Coil", "Shed", "Silent"] },
      { word: "Butterfly", hints: ["Flutter", "Change", "Garden", "Delicate"] },
      { word: "Tiger", hints: ["Prowl", "Stripe", "Roar", "Ambush"] },
      { word: "Rabbit", hints: ["Hop", "Twitch", "Burrow", "Soft"] },
      { word: "Shark", hints: ["Fin", "Circle", "Fear", "Silent"] },
      { word: "Giraffe", hints: ["Reach", "Spot", "Tall", "Grace"] },
      { word: "Panda", hints: ["Roll", "Chew", "Lazy", "Cute"] },
      { word: "Wolf", hints: ["Howl", "Pack", "Moon", "Chase"] },
      { word: "Horse", hints: ["Gallop", "Mane", "Saddle", "Neigh"] },
      { word: "Eagle", hints: ["Soar", "Dive", "Sharp", "Nest"] },
      { word: "Frog", hints: ["Leap", "Croak", "Pond", "Sticky"] },
      { word: "Bear", hints: ["Hibernate", "Claw", "Honey", "Lumber"] },
      { word: "Monkey", hints: ["Swing", "Mischief", "Climb", "Banana"] },
      { word: "Whale", hints: ["Song", "Blow", "Vast", "Dive"] },
      { word: "Fox", hints: ["Sly", "Dusk", "Sneak", "Bushy"] },
      { word: "Turtle", hints: ["Shell", "Slow", "Ancient", "Retreat"] },
      { word: "Lion", hints: ["Mane", "Pride", "Roar", "Nap"] },
      { word: "Deer", hints: ["Freeze", "Dawn", "Grace", "Antler"] },
      { word: "Octopus", hints: ["Ink", "Escape", "Smart", "Grip"] },
      { word: "Bee", hints: ["Buzz", "Sting", "Busy", "Hive"] },
      { word: "Crocodile", hints: ["Snap", "Wait", "Smile", "Lurk"] },
      { word: "Peacock", hints: ["Fan", "Show", "Strut", "Pride"] },
      { word: "Hedgehog", hints: ["Curl", "Prickle", "Snuffle", "Night"] },
      { word: "Flamingo", hints: ["Balance", "Pink", "Stand", "Pose"] },
      { word: "Koala", hints: ["Cling", "Sleep", "Chew", "Slow"] },
      { word: "Seal", hints: ["Bark", "Slap", "Sun", "Slide"] },
      { word: "Bat", hints: ["Hang", "Echo", "Night", "Flutter"] },
      { word: "Camel", hints: ["Endure", "Hump", "Spit", "Trek"] },
      { word: "Parrot", hints: ["Copy", "Squawk", "Color", "Perch"] },
      { word: "Jellyfish", hints: ["Drift", "Sting", "Glow", "Soft"] },
      { word: "Squirrel", hints: ["Dash", "Hide", "Twitch", "Climb"] },
      { word: "Zebra", hints: ["Stripe", "Dash", "Herd", "Dust"] },
      { word: "Hippo", hints: ["Yawn", "Splash", "Heavy", "Grunt"] },
      { word: "Chameleon", hints: ["Blend", "Wait", "Flick", "Still"] },
      { word: "Otter", hints: ["Float", "Play", "Slide", "Hold"] },
      { word: "Raccoon", hints: ["Mask", "Rummage", "Night", "Clever"] },
      { word: "Pelican", hints: ["Scoop", "Dive", "Pouch", "Coast"] },
      { word: "Moose", hints: ["Tower", "Crash", "Northern", "Lone"] },
      { word: "Crab", hints: ["Sidestep", "Pinch", "Scuttle", "Shell"] },
      { word: "Sloth", hints: ["Hang", "Yawn", "Slow", "Upside"] },
      { word: "Platypus", hints: ["Odd", "Swim", "Bill", "Secret"] },
      { word: "Gorilla", hints: ["Chest", "Troop", "Gentle", "Power"] },
      { word: "Lobster", hints: ["Pinch", "Boil", "Crawl", "Armor"] },
      { word: "Ant", hints: ["Carry", "Line", "Tiny", "Team"] },
      { word: "Peacock mantis shrimp", hints: ["Punch", "Flash", "Strike", "Color"] },
    ],
  },
  {
    id: "places",
    name: "Places",
    emoji: "🌍",
    words: [
      { word: "Beach", hints: ["Barefoot", "Salt", "Towel", "Horizon"] },
      { word: "Hospital", hints: ["Beep", "White", "Wait", "Quiet"] },
      { word: "Airport", hints: ["Queue", "Delay", "Gate", "Luggage"] },
      { word: "Library", hints: ["Whisper", "Dust", "Shelf", "Stamp"] },
      { word: "Stadium", hints: ["Roar", "Wave", "Seat", "Chant"] },
      { word: "Museum", hints: ["Whisper", "Glass", "Tour", "Old"] },
      { word: "Restaurant", hints: ["Menu", "Tip", "Wait", "Candle"] },
      { word: "School", hints: ["Bell", "Desk", "Hall", "Homework"] },
      { word: "Mountain", hints: ["Thin", "Echo", "Climb", "Cloud"] },
      { word: "Cinema", hints: ["Dark", "Popcorn", "Trailer", "Seat"] },
      { word: "Park", hints: ["Bench", "Jog", "Picnic", "Shade"] },
      { word: "Supermarket", hints: ["Cart", "Aisle", "Beep", "Bag"] },
      { word: "Hotel", hints: ["Keycard", "Lobby", "Towel", "Floor"] },
      { word: "Zoo", hints: ["Fence", "Map", "Snack", "Crowd"] },
      { word: "Church", hints: ["Echo", "Candle", "Quiet", "Sunday"] },
      { word: "Gym", hints: ["Sweat", "Mirror", "Rep", "Locker"] },
      { word: "Amusement park", hints: ["Queue", "Scream", "Ticket", "Sugar"] },
      { word: "Post office", hints: ["Stamp", "Queue", "Parcel", "Form"] },
      { word: "Bank", hints: ["Queue", "Vault", "PIN", "Guard"] },
      { word: "Farm", hints: ["Dawn", "Mud", "Smell", "Fence"] },
      { word: "Desert", hints: ["Mirage", "Thirst", "Heat", "Empty"] },
      { word: "Island", hints: ["Ferry", "Alone", "Palm", "Escape"] },
      { word: "Forest", hints: ["Shade", "Crunch", "Moss", "Lost"] },
      { word: "Subway station", hints: ["Rush", "Echo", "Swipe", "Tunnel"] },
      { word: "Shopping mall", hints: ["Escalator", "Echo", "Sale", "Foodcourt"] },
      { word: "Aquarium", hints: ["Glass", "Blue", "Bubble", "Dim"] },
      { word: "Castle", hints: ["Stone", "Tour", "Draft", "Tower"] },
      { word: "Campground", hints: ["Smoke", "Zip", "Stars", "Bug"] },
      { word: "Office", hints: ["Cubicle", "Coffee", "Meeting", "Deadline"] },
      { word: "Harbor", hints: ["Horn", "Rope", "Salt", "Dock"] },
      { word: "Observatory", hints: ["Dome", "Night", "Focus", "Cold"] },
      { word: "Prison", hints: ["Bars", "Visit", "Count", "Gray"] },
      { word: "Cemetery", hints: ["Quiet", "Stone", "Flower", "Wind"] },
      { word: "Marketplace", hints: ["Haggle", "Smell", "Crowd", "Stall"] },
      { word: "Volcano", hints: ["Rumble", "Ash", "Heat", "Smoke"] },
      { word: "Waterfall", hints: ["Roar", "Mist", "Slip", "Echo"] },
      { word: "Lighthouse", hints: ["Beam", "Storm", "Lonely", "Cliff"] },
      { word: "Cave", hints: ["Drip", "Echo", "Dark", "Cold"] },
      { word: "University", hints: ["Lecture", "Campus", "Exam", "Dorm"] },
      { word: "Bakery", hints: ["Aroma", "Dawn", "Flour", "Warm"] },
      { word: "Nightclub", hints: ["Bass", "Strobe", "Late", "Crowd"] },
      { word: "Gas station", hints: ["Pump", "Night", "Snack", "Road"] },
      { word: "Courthouse", hints: ["Gavel", "Suit", "Wait", "Formal"] },
      { word: "Playground", hints: ["Squeak", "Laugh", "Sand", "Swing"] },
      { word: "Spa", hints: ["Steam", "Whisper", "Oil", "Calm"] },
      { word: "Train station", hints: ["Announce", "Platform", "Whistle", "Delay"] },
      { word: "Rooftop", hints: ["Wind", "View", "Edge", "City"] },
      { word: "Warehouse", hints: ["Echo", "Forklift", "Dust", "Box"] },
      { word: "Botanical garden", hints: ["Label", "Path", "Humid", "Photo"] },
      { word: "Skatepark", hints: ["Grind", "Fall", "Ramp", "Echo"] },
    ],
  },
  {
    id: "objects",
    name: "Everyday Objects",
    emoji: "📦",
    words: [
      { word: "Umbrella", hints: ["Snap", "Drip", "Wind", "Fold"] },
      { word: "Toothbrush", hints: ["Foam", "Morning", "Mint", "Routine"] },
      { word: "Mirror", hints: ["Fog", "Check", "Double", "Glass"] },
      { word: "Backpack", hints: ["Zip", "Shoulder", "Heavy", "School"] },
      { word: "Candle", hints: ["Flicker", "Wax", "Wish", "Scent"] },
      { word: "Clock", hints: ["Tick", "Late", "Face", "Alarm"] },
      { word: "Pillow", hints: ["Fluff", "Dream", "Soft", "Toss"] },
      { word: "Scissors", hints: ["Snip", "Sharp", "Pair", "Craft"] },
      { word: "Wallet", hints: ["Thin", "Lost", "Fold", "Pocket"] },
      { word: "Key", hints: ["Jingle", "Stuck", "Click", "Spare"] },
      { word: "Phone", hints: ["Buzz", "Scroll", "Charge", "Glow"] },
      { word: "Laptop", hints: ["Fan", "Glow", "Click", "Battery"] },
      { word: "Headphones", hints: ["Mute", "Wire", "Beat", "Escape"] },
      { word: "Pen", hints: ["Scratch", "Cap", "Leak", "Note"] },
      { word: "Notebook", hints: ["Blank", "Spiral", "Doodle", "Margin"] },
      { word: "Bottle", hints: ["Cap", "Sip", "Refill", "Squeeze"] },
      { word: "Chair", hints: ["Creak", "Spin", "Sit", "Legs"] },
      { word: "Lamp", hints: ["Click", "Glow", "Shade", "Night"] },
      { word: "Towel", hints: ["Damp", "Hang", "Fluff", "Steam"] },
      { word: "Remote control", hints: ["Lost", "Click", "Couch", "Battery"] },
      { word: "Sunglasses", hints: ["Slide", "Glare", "Cool", "Case"] },
      { word: "Watch", hints: ["Glance", "Tick", "Strap", "Late"] },
      { word: "Comb", hints: ["Tangle", "Pull", "Pocket", "Smooth"] },
      { word: "Flashlight", hints: ["Click", "Beam", "Dead", "Search"] },
      { word: "Hammer", hints: ["Bang", "Thumb", "Swing", "Nail"] },
      { word: "Plate", hints: ["Clink", "Chip", "Stack", "Spin"] },
      { word: "Spoon", hints: ["Clink", "Scoop", "Stir", "Metal"] },
      { word: "Blanket", hints: ["Cocoon", "Warm", "Heavy", "Nap"] },
      { word: "Shovel", hints: ["Dig", "Dirt", "Lean", "Hole"] },
      { word: "Rope", hints: ["Knot", "Pull", "Coil", "Fray"] },
      { word: "Glue", hints: ["Sticky", "Wait", "Mess", "Cap"] },
      { word: "Tape", hints: ["Tear", "Stick", "Rip", "Roll"] },
      { word: "Basket", hints: ["Carry", "Weave", "Empty", "Handle"] },
      { word: "Thermometer", hints: ["Beep", "Fever", "Wait", "Number"] },
      { word: "Alarm clock", hints: ["Snooze", "Blast", "Dread", "Morning"] },
      { word: "Trash can", hints: ["Lid", "Smell", "Full", "Kick"] },
      { word: "Hanger", hints: ["Hook", "Slip", "Closet", "Wire"] },
      { word: "Soap", hints: ["Slip", "Foam", "Scent", "Bar"] },
      { word: "Bandage", hints: ["Peel", "Ouch", "Wrap", "Sticky"] },
      { word: "Extension cord", hints: ["Trip", "Tangle", "Reach", "Plug"] },
      { word: "Stapler", hints: ["Click", "Jam", "Desk", "Punch"] },
      { word: "Calculator", hints: ["Beep", "Clear", "Exam", "Tiny"] },
      { word: "Envelope", hints: ["Seal", "Stamp", "Tear", "Fold"] },
      { word: "Paintbrush", hints: ["Stroke", "Drip", "Stiff", "Color"] },
      { word: "Ladder", hints: ["Wobble", "Reach", "Rung", "Lean"] },
      { word: "Fan", hints: ["Hum", "Spin", "Breeze", "Dust"] },
      { word: "Iron", hints: ["Steam", "Hiss", "Press", "Hot"] },
      { word: "Vacuum cleaner", hints: ["Roar", "Suck", "Cord", "Dust"] },
      { word: "Suitcase", hints: ["Roll", "Overpack", "Tag", "Zip"] },
      { word: "Doorbell", hints: ["Chime", "Wait", "Peek", "Guest"] },
    ],
  },
  {
    id: "movies",
    name: "Movies & Shows",
    emoji: "🎬",
    words: [
      { word: "Titanic", hints: ["Door", "Sink", "Violin", "Cold"] },
      { word: "Frozen", hints: ["Letgo", "Snow", "Sister", "Castle"] },
      { word: "Harry Potter", hints: ["Scar", "Wand", "Owl", "Platform"] },
      { word: "Star Wars", hints: ["Force", "Sand", "Hope", "Duel"] },
      { word: "Avengers", hints: ["Assemble", "Snap", "Team", "Tower"] },
      { word: "Jurassic Park", hints: ["Fence", "Roar", "Jeep", "Amber"] },
      { word: "The Lion King", hints: ["Circle", "Pride", "Dust", "Uncle"] },
      { word: "Spider-Man", hints: ["Web", "Roof", "Bite", "Mask"] },
      { word: "F.R.I.E.N.D.S.", hints: ["Couch", "Pivot", "Central", "Laugh"] },
      { word: "Squid Game", hints: ["Number", "Doll", "Debt", "Circle"] },
      { word: "The Office", hints: ["Paper", "Awkward", "Desk", "Boss"] },
      { word: "The Big Bang Theory", hints: ["Knock", "Nerd", "Sofa", "Bazinga"] },
      { word: "The Simpsons", hints: ["Yellow", "Doh", "Couch", "Donut"] },
      { word: "Breaking Bad", hints: ["RV", "Blue", "Teacher", "Desert"] },
      { word: "Game of Thrones", hints: ["Winter", "Throne", "Betray", "Fire"] },
      { word: "Stranger Things", hints: ["Bike", "Lights", "Upside", "Walkie"] },
      { word: "The Matrix", hints: ["Pill", "Glitch", "Coat", "Wake"] },
      { word: "Inception", hints: ["Spin", "Fall", "Layer", "Kick"] },
      { word: "Toy Story", hints: ["Shelf", "Lost", "Cowboy", "Buzz"] },
      { word: "Finding Nemo", hints: ["Lost", "Current", "Forget", "Tank"] },
      { word: "Shrek", hints: ["Swamp", "Onion", "Farquaad", "Ogre"] },
      { word: "The Godfather", hints: ["Offer", "Horse", "Family", "Whisper"] },
      { word: "Forrest Gump", hints: ["Run", "Bench", "Box", "Feather"] },
      { word: "Pulp Fiction", hints: ["Briefcase", "Dance", "Diner", "Twist"] },
      { word: "The Shawshank Redemption", hints: ["Poster", "Hope", "Tunnel", "Rain"] },
      { word: "Jaws", hints: ["Theme", "Beach", "Boat", "Fin"] },
      { word: "E.T.", hints: ["Finger", "Bike", "Home", "Glow"] },
      { word: "Back to the Future", hints: ["Clock", "Lightning", "Skate", "Past"] },
      { word: "The Hunger Games", hints: ["Arrow", "Arena", "Mocking", "Tribute"] },
      { word: "Black Panther", hints: ["Vibranium", "Mask", "Throne", "Suit"] },
      { word: "Moana", hints: ["Wave", "Voyage", "Heart", "Ocean"] },
      { word: "Coco", hints: ["Guitar", "Marigold", "Memory", "Bridge"] },
      { word: "The Walking Dead", hints: ["Fence", "Bite", "Camp", "Quiet"] },
      { word: "Seinfeld", hints: ["Nothing", "Soup", "Apartment", "Quirk"] },
      { word: "How I Met Your Mother", hints: ["Umbrella", "Bar", "Story", "Yellow"] },
      { word: "Brooklyn Nine-Nine", hints: ["Precinct", "Joke", "Case", "Squad"] },
      { word: "The Crown", hints: ["Jewel", "Duty", "Palace", "Era"] },
      { word: "Wednesday", hints: ["Dance", "School", "Dark", "Cello"] },
      { word: "Avatar", hints: ["Blue", "Link", "Tree", "Fly"] },
      { word: "Gladiator", hints: ["Arena", "Sand", "Crowd", "Revenge"] },
      { word: "Interstellar", hints: ["Corn", "Watch", "Dust", "Dock"] },
      { word: "La La Land", hints: ["Piano", "Traffic", "Dream", "Dance"] },
      { word: "Parasite", hints: ["Stairs", "Rain", "Smell", "Plan"] },
      { word: "The Mandalorian", hints: ["Bounty", "Helmet", "Child", "Armor"] },
      { word: "WandaVision", hints: ["Sitcom", "Hex", "Grief", "Static"] },
      { word: "Encanto", hints: ["Candle", "Gift", "Crack", "Family"] },
      { word: "Top Gun", hints: ["Jet", "Rival", "Beach", "Need"] },
      { word: "Dune", hints: ["Spice", "Worm", "Prophecy", "Sand"] },
      { word: "Oppenheimer", hints: ["Trinity", "Guilt", "Suit", "Flash"] },
      { word: "Barbie", hints: ["Pink", "Heel", "Box", "Real"] },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    emoji: "⚽",
    words: [
      { word: "Football", hints: ["Whistle", "Crowd", "Pass", "Pitch"] },
      { word: "Basketball", hints: ["Bounce", "Swish", "Dunk", "Sneaker"] },
      { word: "Tennis", hints: ["Grunt", "Ace", "Clay", "Love"] },
      { word: "Swimming", hints: ["Splash", "Breath", "Lane", "Cap"] },
      { word: "Boxing", hints: ["Bell", "Jab", "Corner", "Sweat"] },
      { word: "Golf", hints: ["Quiet", "Swing", "Green", "Caddy"] },
      { word: "Cycling", hints: ["Pedal", "Wind", "Gear", "Pack"] },
      { word: "Skiing", hints: ["Slope", "Fall", "Lift", "Cold"] },
      { word: "Volleyball", hints: ["Spike", "Sand", "Set", "Dive"] },
      { word: "Bowling", hints: ["Gutter", "Spare", "Lane", "Shoe"] },
      { word: "Baseball", hints: ["Diamond", "Catch", "Home", "Cap"] },
      { word: "Cricket", hints: ["Pitch", "Over", "Tea", "Boundary"] },
      { word: "Rugby", hints: ["Scrum", "Mud", "Try", "Tackle"] },
      { word: "Hockey", hints: ["Ice", "Check", "Puck", "Glass"] },
      { word: "Badminton", hints: ["Feather", "Smash", "Net", "Quick"] },
      { word: "Table tennis", hints: ["Ping", "Spin", "Basement", "Rally"] },
      { word: "Archery", hints: ["Breath", "Aim", "Twang", "Bull"] },
      { word: "Fencing", hints: ["Lunge", "Mask", "Touch", "Parry"] },
      { word: "Wrestling", hints: ["Pin", "Mat", "Grip", "Hold"] },
      { word: "Surfing", hints: ["Wipeout", "Wave", "Wax", "Balance"] },
      { word: "Skateboarding", hints: ["Grind", "Fall", "Trick", "Ramp"] },
      { word: "Gymnastics", hints: ["Flip", "Beam", "Stick", "Score"] },
      { word: "Marathon", hints: ["Wall", "Mile", "Crowd", "Medal"] },
      { word: "Triathlon", hints: ["Transition", "Endure", "Three", "Iron"] },
      { word: "Diving", hints: ["Splash", "Board", "Tuck", "Judge"] },
      { word: "Rowing", hints: ["Stroke", "Sync", "Wake", "Cox"] },
      { word: "Sailing", hints: ["Tack", "Wind", "Rope", "Heel"] },
      { word: "Rock climbing", hints: ["Chalk", "Grip", "Fall", "Hold"] },
      { word: "Martial arts", hints: ["Bow", "Belt", "Dojo", "Focus"] },
      { word: "Lacrosse", hints: ["Cradle", "Net", "Fast", "Stick"] },
      { word: "Polo", hints: ["Mallet", "Gallop", "Chukker", "Grass"] },
      { word: "Handball", hints: ["Bounce", "Goal", "Indoor", "Pass"] },
      { word: "Squash", hints: ["Sweat", "Wall", "Echo", "Rally"] },
      { word: "Billiards", hints: ["Chalk", "Break", "Felt", "Angle"] },
      { word: "Darts", hints: ["Pub", "Throw", "Bull", "Oche"] },
      { word: "Weightlifting", hints: ["Grunt", "Bar", "Rack", "PR"] },
      { word: "Figure skating", hints: ["Spin", "Fall", "Music", "Blade"] },
      { word: "Snowboarding", hints: ["Powder", "Edge", "Fall", "Park"] },
      { word: "Motorsport", hints: ["Pit", "Lap", "Roar", "Flag"] },
      { word: "Equestrian", hints: ["Jump", "Saddle", "Trot", "Arena"] },
      { word: "Curling", hints: ["Sweep", "Ice", "Slide", "House"] },
      { word: "Softball", hints: ["Diamond", "Pitch", "Glove", "Inning"] },
      { word: "Water polo", hints: ["Tread", "Goal", "Splash", "Cap"] },
      { word: "Parkour", hints: ["Vault", "Roof", "Flow", "Drop"] },
      { word: "Ultimate frisbee", hints: ["Float", "Catch", "Spirit", "Cut"] },
      { word: "Kickboxing", hints: ["Pad", "Sweat", "Combo", "Guard"] },
      { word: "Bobsled", hints: ["Push", "Ice", "Curve", "Helmet"] },
      { word: "Biathlon", hints: ["Shoot", "Ski", "Breath", "Range"] },
      { word: "Sumo", hints: ["Stomp", "Salt", "Push", "Circle"] },
      { word: "Cheerleading", hints: ["Pyramid", "Chant", "Toss", "Pom"] },
    ],
  },
  {
    id: "esports",
    name: "Esports",
    emoji: "🎮",
    words: [
      { word: "League of Legends", hints: ["Lane", "Baron", "Flash", "Draft"] },
      { word: "Valorant", hints: ["Spike", "Eco", "Wall", "Clutch"] },
      { word: "Fortnite", hints: ["Storm", "Build", "Emote", "Drop"] },
      { word: "Overwatch", hints: ["Ult", "Payload", "Role", "Res"] },
      { word: "Dota 2", hints: ["Roshan", "Courier", "Draft", "Aegis"] },
      { word: "CS:GO", hints: ["Eco", "Smoke", "Plant", "Ace"] },
      { word: "PUBG", hints: ["Circle", "Loot", "Chicken", "Drop"] },
      { word: "Apex Legends", hints: ["Ping", "Banner", "Third", "Drop"] },
      { word: "Rainbow Six Siege", hints: ["Breach", "Cam", "Wall", "Plant"] },
      { word: "Call of Duty", hints: ["Loadout", "Killstreak", "Camp", "Respawn"] },
      { word: "FIFA", hints: ["FUT", "Pace", "Script", "Whistle"] },
      { word: "Minecraft", hints: ["Craft", "Mine", "Night", "Block"] },
      { word: "Roblox", hints: ["Avatar", "Obby", "Coin", "Lobby"] },
      { word: "Stumble Guys", hints: ["Fall", "Round", "Crowd", "Bean"] },
      { word: "Rocket League", hints: ["Boost", "Aerial", "Demo", "Kickoff"] },
      { word: "Super Smash Bros", hints: ["Stock", "Edge", "Stage", "Combo"] },
      { word: "Street Fighter", hints: ["Hadouken", "Round", "Combo", "Block"] },
      { word: "Tekken", hints: ["Rage", "Wall", "Combo", "Round"] },
      { word: "Hearthstone", hints: ["Mana", "Draw", "Board", "Legend"] },
      { word: "StarCraft II", hints: ["Macro", "Rush", "Scout", "Base"] },
      { word: "Age of Empires", hints: ["Age", "Villager", "Wonder", "Scout"] },
      { word: "Clash Royale", hints: ["Elixir", "Tower", "Cycle", "Push"] },
      { word: "Clash of Clans", hints: ["Raid", "Wall", "Builder", "Trophy"] },
      { word: "Among Us", hints: ["Vent", "Task", "Meeting", "Sus"] },
      { word: "Fall Guys", hints: ["Qualify", "Grab", "Bean", "Final"] },
      { word: "Genshin Impact", hints: ["Wish", "Resin", "Element", "Explore"] },
      { word: "Mobile Legends", hints: ["Lane", "Recall", "Rank", "Push"] },
      { word: "Free Fire", hints: ["Drop", "Zone", "Rank", "Spray"] },
      { word: "Brawl Stars", hints: ["Gem", "Showdown", "Star", "Mode"] },
      { word: "Counter-Strike 2", hints: ["Smoke", "Eco", "Plant", "Skin"] },
      { word: "Teamfight Tactics", hints: ["Reroll", "Augment", "Board", "Trait"] },
      { word: "Halo", hints: ["Shield", "Forge", "Arena", "Spartan"] },
      { word: "Smite", hints: ["God", "Jungle", "Ult", "Lane"] },
      { word: "Paladins", hints: ["Card", "Point", "Ult", "Champ"] },
      { word: "Warzone", hints: ["Gulag", "Loadout", "Circle", "Buy"] },
      { word: "Dead by Daylight", hints: ["Hook", "Gen", "Chase", "Fog"] },
      { word: "League of Legends Wild Rift", hints: ["Lane", "Flash", "Rank", "Short"] },
      { word: "Pokémon Unite", hints: ["Score", "Jungle", "Unite", "Lane"] },
      { word: "EA Sports FC", hints: ["FUT", "Pace", "Meta", "Whistle"] },
      { word: "NBA 2K", hints: ["Park", "Badge", "Dunk", "MyCareer"] },
      { word: "Gran Turismo", hints: ["Lap", "Tune", "License", "Drift"] },
      { word: "F1 Esports", hints: ["DRS", "Pit", "Pole", "Sector"] },
      { word: "osu!", hints: ["Combo", "Miss", "Map", "Click"] },
      { word: "Geometry Dash", hints: ["Spike", "Practice", "Cube", "Fail"] },
      { word: "Terraria", hints: ["Boss", "Dig", "Craft", "Biome"] },
      { word: "World of Warcraft", hints: ["Raid", "Mount", "Quest", "Guild"] },
      { word: "Final Fantasy XIV", hints: ["Duty", "Glam", "Raid", "Aether"] },
      { word: "Elden Ring", hints: ["Grace", "Horse", "Death", "Fog"] },
      { word: "Splatoon", hints: ["Turf", "Ink", "Squid", "Rank"] },
      { word: "Marvel Rivals", hints: ["Ult", "Point", "Team", "Hero"] },
    ],
  },
  {
    id: "hiking",
    name: "Hiking",
    emoji: "🥾",
    words: [
      { word: "Beg galas", hints: ["Bahu", "Berat", "Peluh", "Zip"] },
      { word: "Denai", hints: ["Ikut", "Tanda", "Debu", "Langkah"] },
      { word: "But hiking", hints: ["Basah", "Geseran", "Tali", "Lumpur"] },
      { word: "Khemah", hints: ["Zip", "Angin", "Malam", "Tiang"] },
      { word: "Kompas", hints: ["Putar", "Hilang", "Utara", "Ragu"] },
      { word: "Peta", hints: ["Lipat", "Basah", "Cari", "Garis"] },
      { word: "Puncak", hints: ["Nafas", "Selfie", "Angin", "Akhir"] },
      { word: "Air terjun", hints: ["Bising", "Basah", "Sejuk", "Gema"] },
      { word: "Botol air", hints: ["Kosong", "Haus", "Sip", "Berat"] },
      { word: "Beg tidur", hints: ["Sempit", "Dingin", "Zip", "Mimpi"] },
      { word: "Lampu suluh", hints: ["Klik", "Gelap", "Mati", "Cari"] },
      { word: "Tongkat hiking", hints: ["Klik", "Irama", "Lutut", "Sepasang"] },
      { word: "Api unggun", hints: ["Asap", "Cerita", "Hangat", "Bara"] },
      { word: "Campuran kacang", hints: ["Renyah", "Beg", "Tenaga", "Garam"] },
      { word: "Altitud", hints: ["Pening", "Nafas", "Nipis", "Perlahan"] },
      { word: "Laluan berliku", hints: ["Bosan", "Panjang", "Ulang", "Naik"] },
      { word: "Rabung", hints: ["Angin", "Sempit", "Jatuh", "Langit"] },
      { word: "Lembah", hints: ["Teduh", "Sungai", "Rendah", "Sejuk"] },
      { word: "Lecet", hints: ["Ouch", "Plaster", "Geseran", "Jalan"] },
      { word: "Jaket hujan", hints: ["Berpeluh", "Berdesir", "Basah", "Zip"] },
      { word: "Lampu kepala", hints: ["Dahi", "Gelap", "Bateri", "Tangan"] },
      { word: "Kit kecemasan", hints: ["Harap", "Tak pakai", "Beg", "Takut"] },
      { word: "Tapak perkhemahan", hints: ["Rata", "Batu", "Malam", "Senyap"] },
      { word: "Dapur gas", hints: ["Klik", "Rebus", "Angin", "Hangat"] },
      { word: "Hammock", hints: ["Ayun", "Pokok", "Rehat", "Goyang"] },
      { word: "Hidupan liar", hints: ["Senyap", "Takut", "Jauh", "Gerak"] },
      { word: "Semburan beruang", hints: ["Takut", "Tin", "Jauh", "Harap"] },
      { word: "GPS", hints: ["Beep", "Hilang", "Isyarat", "Tunggu"] },
      { word: "Kenaikan elevasi", hints: ["Nafas", "Statistik", "Sakit", "Perlahan"] },
      { word: "Hiking sehari", hints: ["Pulang", "Ringan", "Petang", "Cepat"] },
      { word: "Hiking jarak jauh", hints: ["Bulan", "Luka", "Bandar", "Lama"] },
      { word: "Pemandangan", hints: ["Selfie", "Diam", "Wow", "Angin"] },
      { word: "Lumpur", hints: ["Licin", "Kotor", "Jatuh", "Berat"] },
      { word: "Matahari terbit", hints: ["Awal", "Sejuk", "Senyap", "Emas"] },
      { word: "Matahari terbenam", hints: ["Oranye", "Cepat", "Foto", "Petang"] },
      { word: "Anak sungai", hints: ["Basah", "Sejuk", "Langkah", "Batu"] },
      { word: "Jambatan", hints: ["Goyang", "Kayu", "Hati-hati", "Seberang"] },
      { word: "Menara pandang", hints: ["Tangga", "Angin", "Foto", "Tinggi"] },
      { word: "Taman negara", hints: ["Yuran", "Papan", "Ramai", "Peraturan"] },
      { word: "Permit", hints: ["Kuota", "Antri", "Kertas", "Lulus"] },
      { word: "Berlapis pakaian", hints: ["Tanggal", "Peluh", "Dingin", "Beg"] },
      { word: "Stoking", hints: ["Basah", "Bau", "Ganti", "Geseran"] },
      { word: "Penolak serangga", hints: ["Bau", "Sembur", "Gigit", "Malam"] },
      { word: "Losyen matahari", hints: ["Lengket", "Terlupa", "Merah", "Bau"] },
      { word: "Wisel", hints: ["Tiup", "Takut", "Bunyi", "Harap"] },
      { word: "Alat pelbagai guna", hints: ["Poket", "Berguna", "Berat", "Buka"] },
      { word: "Beg kalis air", hints: ["Basah", "Gulung", "Takut", "Sungai"] },
      { word: "Glasier", hints: ["Biru", "Licin", "Sejuk", "Perlahan"] },
      { word: "Hutan", hints: ["Teduh", "Bunyi", "Lembap", "Hilang"] },
      { word: "Padang rumput", hints: ["Terbuka", "Angin", "Serangga", "Cerah"] },
      { word: "Berat beg", hints: ["Regret", "Gram", "Peluh", "Perlahan"] },
      { word: "Hari rehat", hints: ["Mandi", "Tidur", "Bandar", "Luka"] },
      { word: "Penanda denai", hints: ["Ragu", "Cari", "Cat", "Legar"] },
      { word: "Pacak", hints: ["Nafas", "Lutut", "Peluh", "Perlahan"] },
      { word: "Landai", hints: ["Santai", "Langkah", "Senang", "Tenang"] },
    ],
  },
];

export function randomWord(category: Category): WordEntry {
  return category.words[Math.floor(Math.random() * category.words.length)];
}

export function randomHint(entry: WordEntry): string {
  return entry.hints[Math.floor(Math.random() * entry.hints.length)];
}
