export interface WordEntry {
  /** The secret word the crew receives. */
  word: string;
  /** Vague clues for the impostor — at least 3. One is shown at random each round. */
  hints: string[];
}

export interface Category {
  id: string;
  name: string;
  emoji: string;
  words: WordEntry[];
}

export const CATEGORIES: Category[] = [
  {
    id: "food",
    name: "Food & Drink",
    emoji: "🍕",
    words: [
      { word: "Pizza", hints: ["Something you order for a group", "Often delivered", "Has slices", "Topped with cheese"] },
      { word: "Sushi", hints: ["Often eaten with chopsticks", "Served cold", "Japanese cuisine", "Sometimes wrapped in seaweed"] },
      { word: "Pancake", hints: ["A breakfast food", "Often stacked", "Goes with syrup", "Cooked on a griddle"] },
      { word: "Coffee", hints: ["A morning drink", "Can be hot or iced", "Contains caffeine", "Often paired with milk"] },
      { word: "Ice cream", hints: ["A cold dessert", "Comes in many flavors", "Melts quickly", "Served in a cone or cup"] },
      { word: "Hamburger", hints: ["Fast food", "Has a bun", "Eaten with your hands", "Often comes with fries"] },
      { word: "Spaghetti", hints: ["An Italian dish", "Long and thin", "Served with sauce", "Twirled on a fork"] },
      { word: "Popcorn", hints: ["A movie snack", "Made from a seed", "Comes in a bucket", "Buttery and salty"] },
      { word: "Chocolate", hints: ["A sweet treat", "Often given as a gift", "Can melt", "Comes in bars or boxes"] },
      { word: "Watermelon", hints: ["A summer fruit", "Has seeds", "Mostly water", "Red and juicy inside"] },
      { word: "Tacos", hints: ["A handheld meal", "Often spicy", "Wrapped in a shell", "Popular street food"] },
      { word: "Ramen", hints: ["A hot noodle soup", "Japanese comfort food", "Comes in a bowl", "Often topped with an egg"] },
      { word: "Donut", hints: ["A sweet breakfast item", "Has a hole in the middle", "Often glazed", "Sold by the dozen"] },
      { word: "Smoothie", hints: ["A blended drink", "Made from fruit", "Served cold", "Often healthy"] },
      { word: "Steak", hints: ["A grilled meat dish", "Often ordered by doneness", "Served at restaurants", "Cut with a knife"] },
      { word: "Salad", hints: ["Often considered healthy", "Made with greens", "Can be a side or main", "Dressed before eating"] },
      { word: "Burrito", hints: ["A wrapped meal", "Often large", "Filled with rice and beans", "Mexican-inspired"] },
      { word: "Waffles", hints: ["A breakfast grid pattern", "Goes with syrup", "Crispy outside", "Often served with fruit"] },
      { word: "Hot dog", hints: ["A street food classic", "Served in a bun", "Often at ball games", "Topped with condiments"] },
      { word: "Cheesecake", hints: ["A rich dessert", "Creamy texture", "Often has a crust", "Comes in many flavors"] },
      { word: "Milkshake", hints: ["A thick cold drink", "Blended with ice cream", "Served with a straw", "Often chocolate or vanilla"] },
      { word: "Fried rice", hints: ["A stir-fried dish", "Uses leftover rice", "Often has vegetables", "Popular takeout item"] },
      { word: "Nachos", hints: ["A shareable snack", "Topped with cheese", "Often at parties", "Crunchy chips as a base"] },
      { word: "Curry", hints: ["A spiced dish", "Often served with rice", "Popular in many cultures", "Can be mild or hot"] },
      { word: "Bagel", hints: ["A round bread", "Often toasted", "Has a hole in the center", "Popular in the morning"] },
      { word: "Croissant", hints: ["A flaky pastry", "French origin", "Buttery layers", "Often eaten at breakfast"] },
      { word: "Lemonade", hints: ["A refreshing drink", "Sweet and tart", "Popular in summer", "Made from citrus"] },
      { word: "Brownie", hints: ["A chocolate dessert", "Dense and fudgy", "Often square-shaped", "Baked in a pan"] },
      { word: "Sushi roll", hints: ["Rolled and sliced", "Often has rice outside", "Eaten in pieces", "Sometimes has fish inside"] },
      { word: "Pho", hints: ["A Vietnamese soup", "Long noodles in broth", "Often garnished with herbs", "Served in a large bowl"] },
      { word: "Mac and cheese", hints: ["A comfort food", "Pasta with sauce", "Popular with kids", "Creamy and cheesy"] },
      { word: "Apple pie", hints: ["A classic dessert", "Often served warm", "Has a flaky crust", "Associated with tradition"] },
      { word: "Omelette", hints: ["Made from beaten eggs", "A breakfast staple", "Can be filled inside", "Cooked in a pan"] },
      { word: "French fries", hints: ["A salty side dish", "Deep fried", "Often with ketchup", "Crispy and golden"] },
      { word: "Soda", hints: ["A fizzy drink", "Comes in cans or bottles", "Often sugary", "Served with ice"] },
      { word: "Pretzel", hints: ["A twisted snack", "Often salty", "Popular at fairs", "Can be soft or hard"] },
      { word: "Muffin", hints: ["A baked breakfast item", "Comes in flavors", "Often has blueberries", "Individual portion size"] },
      { word: "Lasagna", hints: ["Layered Italian dish", "Baked in the oven", "Has pasta sheets", "Often feeds a crowd"] },
      { word: "Guacamole", hints: ["A green dip", "Made from avocado", "Popular with chips", "Often at parties"] },
      { word: "Tea", hints: ["A hot beverage", "Can be herbal", "Often served in a cup", "Popular worldwide"] },
      { word: "Cupcake", hints: ["A small cake", "Has frosting on top", "Individual serving", "Popular at birthdays"] },
      { word: "Falafel", hints: ["A fried ball snack", "Often in pita bread", "Made from chickpeas", "Middle Eastern origin"] },
      { word: "Paella", hints: ["A rice-based dish", "Spanish origin", "Often has seafood", "Cooked in a wide pan"] },
      { word: "Cereal", hints: ["A quick breakfast", "Eaten with milk", "Comes in a box", "Often crunchy"] },
      { word: "Dumplings", hints: ["Filled dough pockets", "Can be steamed or fried", "Popular in many cuisines", "Often dipped in sauce"] },
      { word: "Popsicle", hints: ["A frozen treat on a stick", "Popular with kids", "Comes in fruity flavors", "Melts in the sun"] },
      { word: "Chili", hints: ["A hearty stew", "Often spicy", "Has beans", "Popular in cold weather"] },
      { word: "Scone", hints: ["A baked pastry", "Often with tea", "Can be plain or fruity", "Slightly crumbly texture"] },
      { word: "Bubble tea", hints: ["A trendy drink", "Has chewy pearls", "Often sweet", "Served with a wide straw"] },
      { word: "Pad thai", hints: ["A stir-fried noodle dish", "Thai street food", "Sweet and savory", "Often has peanuts"] },
    ],
  },
  {
    id: "animals",
    name: "Animals",
    emoji: "🦁",
    words: [
      { word: "Elephant", hints: ["A very large animal", "Has a long nose", "Never forgets", "Has big ears"] },
      { word: "Penguin", hints: ["Lives somewhere cold", "A bird that can't fly", "Black and white", "Waddles on land"] },
      { word: "Dolphin", hints: ["Lives in the water", "Very intelligent", "Often seen jumping", "Makes clicking sounds"] },
      { word: "Kangaroo", hints: ["An animal that jumps", "Carries young in a pouch", "From Australia", "Has strong hind legs"] },
      { word: "Owl", hints: ["Active at night", "Can turn its head far", "A bird of prey", "Known for hooting"] },
      { word: "Snake", hints: ["A reptile", "Has no legs", "Some are venomous", "Slithers on the ground"] },
      { word: "Butterfly", hints: ["A small flying creature", "Was once a caterpillar", "Has colorful wings", "Loves flowers"] },
      { word: "Tiger", hints: ["A wild predator", "Has stripes", "A big cat", "Lives in the jungle"] },
      { word: "Rabbit", hints: ["A common pet", "Has long ears", "Hops around", "Loves carrots"] },
      { word: "Shark", hints: ["A dangerous sea animal", "Has many teeth", "Has a fin", "Lives in the ocean"] },
      { word: "Giraffe", hints: ["Very tall neck", "Spotted pattern", "Eats leaves from trees", "Lives on the savanna"] },
      { word: "Panda", hints: ["Black and white bear", "Eats bamboo", "Native to China", "Often seen as cute"] },
      { word: "Wolf", hints: ["A wild canine", "Howls at night", "Lives in packs", "Known for hunting"] },
      { word: "Horse", hints: ["A large mammal", "People ride them", "Has a mane", "Gallops fast"] },
      { word: "Eagle", hints: ["A bird of prey", "Has sharp vision", "Symbol of strength", "Builds nests in high places"] },
      { word: "Frog", hints: ["Lives near water", "Can jump far", "Starts as a tadpole", "Croaks loudly"] },
      { word: "Bear", hints: ["A large mammal", "Hibernates in winter", "Can be dangerous", "Loves honey"] },
      { word: "Monkey", hints: ["Lives in trees", "Very agile", "Has a tail", "Eats fruit and nuts"] },
      { word: "Whale", hints: ["The largest sea animal", "Blows water from a spout", "Sings underwater", "Migrates long distances"] },
      { word: "Fox", hints: ["A clever wild animal", "Has a bushy tail", "Orange fur", "Active at dusk"] },
      { word: "Turtle", hints: ["Has a hard shell", "Moves slowly", "Can live a long time", "Lives on land or water"] },
      { word: "Lion", hints: ["King of the jungle", "Has a mane", "Lives in prides", "A big cat"] },
      { word: "Deer", hints: ["Has antlers", "Lives in forests", "Skittish and fast", "Often seen at dawn"] },
      { word: "Octopus", hints: ["Lives in the ocean", "Has eight arms", "Can change color", "Very intelligent"] },
      { word: "Bee", hints: ["Makes honey", "Lives in a hive", "Can sting", "Pollinates flowers"] },
      { word: "Crocodile", hints: ["A large reptile", "Lives in water", "Has powerful jaws", "Ancient species"] },
      { word: "Peacock", hints: ["Has colorful feathers", "Fans out its tail", "A type of bird", "Known for display"] },
      { word: "Hedgehog", hints: ["Small and spiky", "Rolls into a ball", "Nocturnal creature", "Eats insects"] },
      { word: "Flamingo", hints: ["Stands on one leg", "Bright pink color", "Lives near water", "A wading bird"] },
      { word: "Koala", hints: ["Lives in trees", "Eats eucalyptus", "From Australia", "Sleeps a lot"] },
      { word: "Seal", hints: ["Lives in cold waters", "Barks loudly", "Has flippers", "Loves to sunbathe"] },
      { word: "Bat", hints: ["The only flying mammal", "Active at night", "Uses echolocation", "Hangs upside down"] },
      { word: "Camel", hints: ["Has humps on its back", "Lives in deserts", "Can go without water", "Used for transport"] },
      { word: "Parrot", hints: ["A colorful bird", "Can mimic sounds", "Lives in tropical areas", "Has a curved beak"] },
      { word: "Jellyfish", hints: ["Lives in the ocean", "Has no bones", "Can sting", "Drifts with currents"] },
      { word: "Squirrel", hints: ["Lives in trees", "Stores nuts", "Has a bushy tail", "Very quick"] },
      { word: "Zebra", hints: ["Has black and white stripes", "Lives on the savanna", "Related to horses", "Travels in herds"] },
      { word: "Hippo", hints: ["Very large mammal", "Lives in rivers", "Has a big mouth", "Spends time in water"] },
      { word: "Chameleon", hints: ["Can change color", "Has a long tongue", "Lives in trees", "Moves very slowly"] },
      { word: "Otter", hints: ["Plays in the water", "Very social", "Uses tools", "Has a sleek body"] },
      { word: "Raccoon", hints: ["Has a masked face", "Active at night", "Very clever", "Loves trash bins"] },
      { word: "Pelican", hints: ["A large water bird", "Has a big pouch", "Catches fish", "Often seen near coasts"] },
      { word: "Moose", hints: ["Very large deer", "Has wide antlers", "Lives in northern forests", "Tall and lanky"] },
      { word: "Crab", hints: ["Walks sideways", "Has claws", "Lives near the shore", "Has a hard shell"] },
      { word: "Sloth", hints: ["Moves very slowly", "Lives in trees", "Sleeps most of the day", "Has long claws"] },
      { word: "Platypus", hints: ["Lays eggs", "Has a duck-like bill", "From Australia", "A very unusual mammal"] },
      { word: "Gorilla", hints: ["A large ape", "Lives in groups", "Very strong", "Mostly herbivorous"] },
      { word: "Lobster", hints: ["Lives in the ocean", "Has large claws", "Considered a delicacy", "Red when cooked"] },
      { word: "Ant", hints: ["Very small insect", "Lives in colonies", "Can carry heavy loads", "Works together"] },
      { word: "Peacock mantis shrimp", hints: ["Lives in the ocean", "Has powerful claws", "Extremely colorful", "Packs a surprising punch"] },
    ],
  },
  {
    id: "places",
    name: "Places",
    emoji: "🌍",
    words: [
      { word: "Beach", hints: ["A place you go to relax", "Has sand", "Near the water", "People sunbathe here"] },
      { word: "Hospital", hints: ["A building with staff in uniform", "You go when sick", "Has beds and machines", "Doctors work here"] },
      { word: "Airport", hints: ["A place full of travelers", "Has security checks", "People wait here", "Planes take off nearby"] },
      { word: "Library", hints: ["A quiet public place", "Full of books", "You borrow things here", "Silence is expected"] },
      { word: "Stadium", hints: ["A place for big crowds", "Has many seats", "Events happen here", "Fans cheer loudly"] },
      { word: "Museum", hints: ["A place you visit to learn", "Has exhibits", "Things are on display", "Often has guided tours"] },
      { word: "Restaurant", hints: ["A place you pay to be served", "Has a menu", "You eat here", "A waiter may come to your table"] },
      { word: "School", hints: ["A place with daily routines", "Has classrooms", "You learn here", "Students attend daily"] },
      { word: "Mountain", hints: ["Somewhere outdoors", "Very tall", "People climb it", "Often has snow at the top"] },
      { word: "Cinema", hints: ["A place for entertainment", "It's dark inside", "Has a big screen", "You buy tickets at the door"] },
      { word: "Park", hints: ["A green public space", "Has benches and paths", "Kids play here", "Good for picnics"] },
      { word: "Supermarket", hints: ["You buy groceries here", "Has aisles and carts", "Open to the public", "Self-checkout may be available"] },
      { word: "Hotel", hints: ["You stay overnight here", "Has a front desk", "Rooms have beds", "Often has a pool"] },
      { word: "Zoo", hints: ["Animals are kept here", "Families visit on weekends", "Has enclosures", "Educational signs everywhere"] },
      { word: "Church", hints: ["A place of worship", "Often has stained glass", "People gather on Sundays", "Has rows of pews"] },
      { word: "Gym", hints: ["A place to exercise", "Has weights and machines", "People work out here", "Often requires membership"] },
      { word: "Amusement park", hints: ["Full of rides", "People wait in lines", "Lots of excitement", "Often has a mascot"] },
      { word: "Post office", hints: ["You send packages here", "Government building", "Has stamps and mail", "Long queues sometimes"] },
      { word: "Bank", hints: ["You keep money here", "Has tellers", "ATMs nearby", "Security is tight"] },
      { word: "Farm", hints: ["Grows crops or animals", "Rural location", "Early mornings are busy", "Tractors are common"] },
      { word: "Desert", hints: ["Very dry landscape", "Extreme temperatures", "Few people live here", "Sand or rock stretches far"] },
      { word: "Island", hints: ["Surrounded by water", "May be tropical", "Hard to reach by car", "Often a vacation spot"] },
      { word: "Forest", hints: ["Full of trees", "Animals live here", "Can be dark inside", "Good for hiking"] },
      { word: "Subway station", hints: ["Underground transport hub", "Trains arrive on schedule", "People rush through", "Has turnstiles"] },
      { word: "Shopping mall", hints: ["Many stores in one building", "Has a food court", "Indoor and air-conditioned", "Popular on weekends"] },
      { word: "Aquarium", hints: ["Fish behind glass", "Educational and fun", "Often near water", "Dark with blue lighting"] },
      { word: "Castle", hints: ["An old fortified building", "Often on a hill", "Tourist attraction", "Has thick stone walls"] },
      { word: "Campground", hints: ["People sleep in tents", "Outdoors at night", "Has fire pits", "Nature surrounds you"] },
      { word: "Office", hints: ["People work at desks", "Has meetings", "Business happens here", "Usually weekdays only"] },
      { word: "Harbor", hints: ["Boats dock here", "Near the coast", "Smells like the sea", "Fishing boats common"] },
      { word: "Observatory", hints: ["Studies the stars", "Has a large telescope", "Often on a hilltop", "Open at night"] },
      { word: "Prison", hints: ["People are held here", "High walls and fences", "Very secure", "Visits are restricted"] },
      { word: "Cemetery", hints: ["A quiet resting place", "Has headstones", "People visit to remember", "Often has flowers"] },
      { word: "Marketplace", hints: ["Vendors sell goods", "Often outdoors", "Bustling and loud", "Fresh produce common"] },
      { word: "Volcano", hints: ["Can erupt", "Very hot inside", "Often cone-shaped", "Lava may flow"] },
      { word: "Waterfall", hints: ["Water falls from height", "Often in nature", "Makes a loud sound", "Mist in the air"] },
      { word: "Lighthouse", hints: ["Guides ships at night", "Stands near the coast", "Has a bright beam", "Tall and isolated"] },
      { word: "Cave", hints: ["Underground space", "Dark inside", "May have stalactites", "Explorers visit with lights"] },
      { word: "University", hints: ["Higher education campus", "Has lecture halls", "Students live nearby", "Large and sprawling"] },
      { word: "Bakery", hints: ["Smells amazing inside", "Fresh bread daily", "Pastries in display cases", "Opens early in the morning"] },
      { word: "Nightclub", hints: ["Loud music inside", "Open late at night", "People dance here", "Has a bar"] },
      { word: "Gas station", hints: ["You fill up your car", "Has a convenience store", "Open 24 hours sometimes", "Located along roads"] },
      { word: "Courthouse", hints: ["Laws are enforced here", "Judges work inside", "Trials take place", "Formal and serious"] },
      { word: "Playground", hints: ["Kids climb and swing", "Has slides", "Outdoor recreation", "Often near a school"] },
      { word: "Spa", hints: ["A place to relax", "Offers massages", "Calm atmosphere", "People go to unwind"] },
      { word: "Train station", hints: ["Trains arrive and depart", "Has platforms", "Tickets sold here", "Announcements over speakers"] },
      { word: "Rooftop", hints: ["At the top of a building", "Great views", "Sometimes has a garden", "Windy up here"] },
      { word: "Warehouse", hints: ["Stores large quantities", "Industrial area", "Forklifts inside", "Few windows"] },
      { word: "Botanical garden", hints: ["Many plant species", "Peaceful paths", "Educational labels", "Great for photos"] },
      { word: "Skatepark", hints: ["Ramps and rails", "Young people gather", "Wheels are common", "Outdoor or indoor"] },
    ],
  },
  {
    id: "objects",
    name: "Everyday Objects",
    emoji: "📦",
    words: [
      { word: "Umbrella", hints: ["Useful in bad weather", "Keeps you dry", "Opens and closes", "Has a handle"] },
      { word: "Toothbrush", hints: ["A daily-use item", "Used in the bathroom", "Has bristles", "Keeps you clean"] },
      { word: "Mirror", hints: ["Found in most homes", "You look into it", "Made of glass", "Reflects your image"] },
      { word: "Backpack", hints: ["Something you carry", "Has straps", "Holds your things", "Worn on your back"] },
      { word: "Candle", hints: ["Gives off light", "Has a wick", "Melts as it burns", "Creates atmosphere"] },
      { word: "Clock", hints: ["Tells you something", "Has hands or numbers", "On the wall", "Tracks time"] },
      { word: "Pillow", hints: ["Found in a bedroom", "Soft", "You rest your head on it", "Comes in pairs on a bed"] },
      { word: "Scissors", hints: ["A handheld tool", "Has two blades", "Used for cutting", "Found in most desks"] },
      { word: "Wallet", hints: ["Keeps things safe", "Fits in a pocket", "Holds cards and cash", "Often leather"] },
      { word: "Key", hints: ["Opens something", "Small and metal", "Goes in a lock", "On a keychain"] },
      { word: "Phone", hints: ["Fits in your pocket", "Used daily", "Has a screen", "Can make calls"] },
      { word: "Laptop", hints: ["Portable computer", "Has a keyboard", "Opens like a book", "Used for work or school"] },
      { word: "Headphones", hints: ["Worn on your ears", "Plays audio privately", "Has a cord or not", "Common on commutes"] },
      { word: "Pen", hints: ["Used for writing", "Has ink inside", "Fits in a pocket", "Runs out eventually"] },
      { word: "Notebook", hints: ["Pages bound together", "Used for notes", "Fits in a bag", "Has lines or grids"] },
      { word: "Bottle", hints: ["Holds liquids", "Has a cap", "Reusable or disposable", "Often plastic or glass"] },
      { word: "Chair", hints: ["You sit on it", "Has four legs", "Found everywhere", "Comes in many styles"] },
      { word: "Lamp", hints: ["Provides light", "Plugs into a wall", "On a desk or floor", "Has a shade"] },
      { word: "Towel", hints: ["Used after bathing", "Absorbs water", "Hung to dry", "Soft fabric"] },
      { word: "Remote control", hints: ["Changes channels", "Has buttons", "Used from the couch", "Needs batteries"] },
      { word: "Sunglasses", hints: ["Worn on your face", "Blocks bright light", "Has dark lenses", "Popular in summer"] },
      { word: "Watch", hints: ["Worn on your wrist", "Tells the time", "May have a strap", "Some are smart"] },
      { word: "Comb", hints: ["Used on hair", "Has teeth", "Found in bathrooms", "Small and portable"] },
      { word: "Flashlight", hints: ["Provides light in the dark", "Needs batteries", "Handheld", "Useful in emergencies"] },
      { word: "Hammer", hints: ["A tool for hitting", "Has a wooden handle", "Found in toolboxes", "Drives nails"] },
      { word: "Plate", hints: ["You eat off it", "Round and flat", "Found in kitchens", "Comes in a set"] },
      { word: "Spoon", hints: ["Used for eating", "Has a bowl shape", "Comes in a set", "Metal or plastic"] },
      { word: "Blanket", hints: ["Keeps you warm", "Used on a bed", "Soft fabric", "Good for snuggling"] },
      { word: "Shovel", hints: ["Used for digging", "Long handle", "Has a flat blade", "Found in gardens"] },
      { word: "Rope", hints: ["Used for tying", "Long and flexible", "Made of fibers", "Strong when pulled"] },
      { word: "Glue", hints: ["Sticks things together", "Comes in a tube or bottle", "Dries over time", "Used in crafts"] },
      { word: "Tape", hints: ["Sticky on one side", "Used for sealing", "Comes in a roll", "Tears easily"] },
      { word: "Basket", hints: ["Used for carrying", "Has a handle", "Woven material", "Good for picnics"] },
      { word: "Thermometer", hints: ["Measures temperature", "Used when sick", "Has a scale", "Goes in your mouth or ear"] },
      { word: "Alarm clock", hints: ["Wakes you up", "Has a loud sound", "Sits on a nightstand", "Set before bed"] },
      { word: "Trash can", hints: ["Holds waste", "Has a lid sometimes", "Emptied regularly", "Found in every room"] },
      { word: "Hanger", hints: ["Holds clothes", "Shaped like shoulders", "Found in closets", "Metal or plastic"] },
      { word: "Soap", hints: ["Used for cleaning", "Gets foamy with water", "Found in bathrooms", "Comes in bars or bottles"] },
      { word: "Bandage", hints: ["Covers a wound", "Has adhesive", "Found in first aid kits", "Small and sticky"] },
      { word: "Extension cord", hints: ["Extends power reach", "Has plugs at both ends", "Useful outdoors", "Can be a trip hazard"] },
      { word: "Stapler", hints: ["Joins papers together", "Uses metal staples", "Found on desks", "Makes a clicking sound"] },
      { word: "Calculator", hints: ["Does math for you", "Has number buttons", "Used in school", "Battery or solar powered"] },
      { word: "Envelope", hints: ["Holds a letter", "Sealed with glue", "Mailed to someone", "Rectangular paper"] },
      { word: "Paintbrush", hints: ["Used for painting", "Has bristles", "Dipped in color", "Comes in many sizes"] },
      { word: "Ladder", hints: ["Helps you reach high places", "Has rungs", "Leans against walls", "Can be dangerous"] },
      { word: "Fan", hints: ["Moves air around", "Spins blades", "Keeps you cool", "Plugs into a wall"] },
      { word: "Iron", hints: ["Removes wrinkles", "Gets very hot", "Used on clothes", "Has a flat metal plate"] },
      { word: "Vacuum cleaner", hints: ["Cleans floors", "Makes a loud noise", "Has a hose", "Sucks up dust"] },
      { word: "Suitcase", hints: ["Used for travel", "Has wheels sometimes", "Packed with clothes", "Goes through airports"] },
      { word: "Doorbell", hints: ["Rings when pressed", "At the front door", "Alerts you to visitors", "Often has a chime"] },
    ],
  },
  {
    id: "movies",
    name: "Movies & Shows",
    emoji: "🎬",
    words: [
      { word: "Titanic", hints: ["A famous romance film", "Involves a ship", "Set on the ocean", "Based on a real disaster"] },
      { word: "Frozen", hints: ["An animated movie", "Has a famous song", "Involves ice and snow", "Two sisters are central"] },
      { word: "Harry Potter", hints: ["Based on books", "Involves magic", "Set at a school", "A boy with a scar"] },
      { word: "Star Wars", hints: ["A sci-fi franchise", "Set in space", "Has a famous villain", "Lightsabers are iconic"] },
      { word: "Avengers", hints: ["A superhero film", "Has a big team", "Lots of action", "Marvel universe"] },
      { word: "Jurassic Park", hints: ["Features creatures", "Set on an island", "Involves science gone wrong", "Dinosaurs return"] },
      { word: "The Lion King", hints: ["An animated classic", "Set in the wild", "Features animals", "A young prince's journey"] },
      { word: "Spider-Man", hints: ["A superhero story", "Involves a teenager", "Has special powers", "Swings between buildings"] },
      { word: "F.R.I.E.N.D.S.", hints: ["A long-running sitcom", "Set in a city", "About a group of people", "Central Perk is iconic"] },
      { word: "Squid Game", hints: ["A survival show", "Involves games", "Has high stakes", "Korean origin"] },
      { word: "The Office", hints: ["A workplace sitcom", "Filmed like a documentary", "Set at a company", "A bumbling boss"] },
      { word: "The Big Bang Theory", hints: ["A sitcom about scientists", "Lots of nerdy humor", "Set in an apartment", "A catchphrase about knocking"] },
      { word: "The Simpsons", hints: ["An animated sitcom", "Has yellow characters", "Running for decades", "Set in a fictional town"] },
      { word: "Breaking Bad", hints: ["A crime drama", "About a chemistry teacher", "Set in the desert", "Transformation story"] },
      { word: "Game of Thrones", hints: ["A fantasy epic", "Many kingdoms at war", "Dragons appear", "Based on books"] },
      { word: "Stranger Things", hints: ["Set in the 1980s", "Involves supernatural events", "Kids are the heroes", "A small town setting"] },
      { word: "The Matrix", hints: ["A sci-fi action film", "Reality is questioned", "Wears dark coats", "Bullet time effects"] },
      { word: "Inception", hints: ["Involves dreams within dreams", "A heist inside the mind", "Directed by Nolan", "A spinning top ending"] },
      { word: "Toy Story", hints: ["Animated film", "Toys come alive", "Pixar classic", "A cowboy and spaceman"] },
      { word: "Finding Nemo", hints: ["An animated ocean adventure", "A father searches", "Pixar film", "A forgetful companion"] },
      { word: "Shrek", hints: ["An ogre as the hero", "A fairy tale parody", "Set in a swamp", "Donkey is a sidekick"] },
      { word: "The Godfather", hints: ["A crime classic", "About a powerful family", "Set in America", "Offers you can't refuse"] },
      { word: "Forrest Gump", hints: ["Runs across the country", "Historical moments woven in", "A box of chocolates metaphor", "Simple but wise protagonist"] },
      { word: "Pulp Fiction", hints: ["Non-linear storytelling", "Directed by Tarantino", "Multiple storylines", "Iconic dance scene"] },
      { word: "The Shawshank Redemption", hints: ["Set in a prison", "About hope and friendship", "A long sentence", "Escape through a tunnel"] },
      { word: "Jaws", hints: ["A thriller at sea", "Something lurks underwater", "Beach town in danger", "You need a bigger boat"] },
      { word: "E.T.", hints: ["An alien visitor", "A boy befriends it", "Wants to phone home", "Spielberg classic"] },
      { word: "Back to the Future", hints: ["Time travel adventure", "A famous car", "Set across decades", "Don't meet your parents"] },
      { word: "The Hunger Games", hints: ["A dystopian competition", "Fights for survival", "Broadcast on TV", "A girl from district twelve"] },
      { word: "Black Panther", hints: ["A superhero from Africa", "Advanced hidden nation", "Marvel film", "Wakanda forever"] },
      { word: "Moana", hints: ["An animated adventure", "Set on the ocean", "A brave young leader", "Disney film"] },
      { word: "Coco", hints: ["Animated film about family", "Day of the Dead theme", "Music is central", "Pixar production"] },
      { word: "The Walking Dead", hints: ["A post-apocalypse show", "Undead roam everywhere", "Survival is the goal", "Long-running series"] },
      { word: "Seinfeld", hints: ["A show about nothing", "Set in New York", "Four friends", "Observational humor"] },
      { word: "How I Met Your Mother", hints: ["A story told in flashback", "Set in New York", "A yellow umbrella", "Nine seasons long"] },
      { word: "Brooklyn Nine-Nine", hints: ["A police comedy", "Set in a precinct", "Very quotable", "A diverse cast"] },
      { word: "The Crown", hints: ["About British royalty", "Historical drama", "Streaming series", "Covers many decades"] },
      { word: "Wednesday", hints: ["A dark comedy series", "A gothic school setting", "Based on a famous family", "Netflix show"] },
      { word: "Avatar", hints: ["Set on another planet", "Blue humanoid creatures", "Highest-grossing film", "Directed by Cameron"] },
      { word: "Gladiator", hints: ["Set in ancient Rome", "Arena combat", "A fallen general", "Are you not entertained"] },
      { word: "Interstellar", hints: ["Space exploration epic", "Time dilation theme", "Directed by Nolan", "A wormhole journey"] },
      { word: "La La Land", hints: ["A musical romance", "Set in Los Angeles", "Dreams vs reality", "Jazz and dancing"] },
      { word: "Parasite", hints: ["A Korean thriller", "Class divide theme", "Won Best Picture", "A wealthy family targeted"] },
      { word: "The Mandalorian", hints: ["A space western series", "Set in a familiar universe", "A bounty hunter hero", "Baby Yoda appears"] },
      { word: "WandaVision", hints: ["A sitcom parody series", "Reality keeps shifting", "Marvel streaming show", "Grief is a theme"] },
      { word: "Encanto", hints: ["An animated musical", "A magical Colombian family", "Disney film", "A house with powers"] },
      { word: "Top Gun", hints: ["About fighter pilots", "Lots of aerial action", "A volleyball scene", "Need for speed"] },
      { word: "Dune", hints: ["Set on a desert planet", "Political intrigue", "A chosen one narrative", "Giant sandworms"] },
      { word: "Oppenheimer", hints: ["A biographical drama", "About the atomic bomb", "Directed by Nolan", "Black and white scenes"] },
      { word: "Barbie", hints: ["A colorful blockbuster", "Based on a famous doll", "Pink everywhere", "Questions identity"] },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    emoji: "⚽",
    words: [
      { word: "Football", hints: ["A team sport", "Played with your feet", "Has goals", "World's most popular sport"] },
      { word: "Basketball", hints: ["Played with a ball", "Involves a hoop", "Lots of jumping", "Played on a court"] },
      { word: "Tennis", hints: ["Played with a racket", "Played over a net", "Can be one-on-one", "Love means zero"] },
      { word: "Swimming", hints: ["Done in water", "An Olympic sport", "Involves different strokes", "Timed in lanes"] },
      { word: "Boxing", hints: ["A combat sport", "Uses gloves", "Fought in a ring", "Rounds with a bell"] },
      { word: "Golf", hints: ["An outdoor sport", "Uses clubs", "Aim for a hole", "Played on a course"] },
      { word: "Cycling", hints: ["Involves a vehicle", "Uses two wheels", "Can be a race", "Tour de France is famous"] },
      { word: "Skiing", hints: ["A winter sport", "Done on snow", "Going downhill", "Uses long boards"] },
      { word: "Volleyball", hints: ["Played over a net", "Played with hands", "Often on a beach", "Six players per side"] },
      { word: "Bowling", hints: ["An indoor activity", "Knock things down", "Roll a ball", "Ten pins to hit"] },
      { word: "Baseball", hints: ["Played with a bat", "Has innings", "Three strikes you're out", "America's pastime"] },
      { word: "Cricket", hints: ["Played with a bat and ball", "Very popular in some countries", "Matches can last days", "Wickets are key"] },
      { word: "Rugby", hints: ["A physical team sport", "An oval ball", "No pads worn", "Popular in the UK"] },
      { word: "Hockey", hints: ["Played on ice or field", "Uses a stick", "A puck or ball", "Fast and physical"] },
      { word: "Badminton", hints: ["Played with a racket", "A shuttlecock flies", "Played over a net", "Very fast reflexes needed"] },
      { word: "Table tennis", hints: ["Played on a small table", "Very fast ball", "Also called ping pong", "Played indoors"] },
      { word: "Archery", hints: ["Uses a bow", "Aim at a target", "Requires steady hands", "Olympic sport"] },
      { word: "Fencing", hints: ["Uses a sword", "One-on-one combat", "Wears protective gear", "Points scored on touch"] },
      { word: "Wrestling", hints: ["Grappling sport", "Pin your opponent", "Very physical", "Ancient Olympic event"] },
      { word: "Surfing", hints: ["Done on waves", "Uses a board", "Balance is key", "Popular in Hawaii"] },
      { word: "Skateboarding", hints: ["Done on a board with wheels", "Tricks and ramps", "Street or park", "Olympic sport now"] },
      { word: "Gymnastics", hints: ["Requires flexibility", "Performed on apparatus", "Judged on form", "Flips and twists"] },
      { word: "Marathon", hints: ["A very long run", "26 miles", "Tests endurance", "Crowds cheer along the route"] },
      { word: "Triathlon", hints: ["Three sports combined", "Swim bike and run", "Very demanding", "Ironman is the famous one"] },
      { word: "Diving", hints: ["Jumps from a platform", "Judged on form", "Enters the water headfirst", "Olympic sport"] },
      { word: "Rowing", hints: ["Done on water", "Uses oars", "Team or solo", "Rhythm is important"] },
      { word: "Sailing", hints: ["Uses wind power", "Done on water", "Has a mast and sails", "Requires navigation skills"] },
      { word: "Rock climbing", hints: ["Scales vertical surfaces", "Uses ropes for safety", "Indoor or outdoor", "Grip strength matters"] },
      { word: "Martial arts", hints: ["Combat discipline", "Many styles exist", "Belt rankings", "Self-defense focus"] },
      { word: "Lacrosse", hints: ["Played with a stick and net", "Fast-paced team sport", "Native American origin", "Played on a field"] },
      { word: "Polo", hints: ["Played on horseback", "Uses a mallet", "Team sport", "Associated with wealth"] },
      { word: "Handball", hints: ["Played with hands", "Team sport indoors", "Throw into a goal", "Popular in Europe"] },
      { word: "Squash", hints: ["Played in a walled court", "Very fast ball", "Two or four players", "Racket sport"] },
      { word: "Billiards", hints: ["Played on a felt table", "Uses a cue stick", "Balls must be pocketed", "Also called pool"] },
      { word: "Darts", hints: ["Thrown at a board", "Played in pubs", "Aim for the bullseye", "Requires accuracy"] },
      { word: "Weightlifting", hints: ["Lifts heavy barbells", "Judged on total weight", "Olympic sport", "Requires immense strength"] },
      { word: "Figure skating", hints: ["Done on ice", "Choreographed routines", "Judged on artistry", "Winter Olympic sport"] },
      { word: "Snowboarding", hints: ["Done on snow", "Uses a single board", "Tricks off jumps", "Winter X Games sport"] },
      { word: "Motorsport", hints: ["Involves vehicles", "Very high speeds", "Raced on tracks", "Formula One is famous"] },
      { word: "Equestrian", hints: ["Involves horses", "Rider and animal together", "Olympic discipline", "Requires training"] },
      { word: "Curling", hints: ["Played on ice", "Slides stones toward a target", "Uses brooms", "Winter Olympic sport"] },
      { word: "Softball", hints: ["Similar to baseball", "Larger ball", "Played on a diamond", "Popular in schools"] },
      { word: "Water polo", hints: ["Played in a pool", "Team sport in water", "Throw a ball at a goal", "Very tiring"] },
      { word: "Parkour", hints: ["Moving through obstacles", "Jumping and climbing", "Urban environment", "Requires agility"] },
      { word: "Ultimate frisbee", hints: ["Throws a disc", "Team sport", "No referees", "Played on a field"] },
      { word: "Kickboxing", hints: ["Striking combat sport", "Uses kicks and punches", "Done in a ring", "Cardio intensive"] },
      { word: "Bobsled", hints: ["Races down ice track", "Team in a sled", "Winter Olympic sport", "Very fast descent"] },
      { word: "Biathlon", hints: ["Combines skiing and shooting", "Winter Olympic sport", "Requires two skills", "Originated in Scandinavia"] },
      { word: "Sumo", hints: ["Japanese wrestling", "Very large athletes", "Ring is sacred", "Push opponent out"] },
      { word: "Cheerleading", hints: ["Supports a team", "Chants and stunts", "Performed at games", "Requires coordination"] },
    ],
  },
  {
    id: "esports",
    name: "Esports",
    emoji: "🎮",
    words: [
      { word: "League of Legends", hints: ["A popular MOBA", "Played in two teams", "Has champions", "Summoner's Rift map"] },
      { word: "Valorant", hints: ["A tactical shooter", "Has agents", "Plant or defuse", "Made by Riot Games"] },
      { word: "Fortnite", hints: ["A battle royale game", "You can build", "Last one standing wins", "Dances are iconic"] },
      { word: "Overwatch", hints: ["A team-based shooter", "Has heroes", "Objective-based", "Made by Blizzard"] },
      { word: "Dota 2", hints: ["A MOBA", "Has a huge prize pool", "Two teams of five", "The International tournament"] },
      { word: "CS:GO", hints: ["A competitive shooter", "Terrorists vs counters", "Buy weapons each round", "Defuse the bomb"] },
      { word: "PUBG", hints: ["A battle royale game", "Drop onto a map", "Shrinking play zone", "Winner winner chicken dinner"] },
      { word: "Apex Legends", hints: ["A battle royale game", "Played in squads", "Has legends with abilities", "Made by Respawn"] },
      { word: "Rainbow Six Siege", hints: ["A tactical shooter", "Attackers vs defenders", "Destructible walls", "Operators with gadgets"] },
      { word: "Call of Duty", hints: ["A first-person shooter", "A long-running series", "Has a campaign and multiplayer", "Warzone is popular"] },
      { word: "FIFA", hints: ["A sports game", "About a popular sport", "Released yearly", "Ultimate Team mode"] },
      { word: "Minecraft", hints: ["A sandbox game", "Made of blocks", "You can build anything", "Creepers are dangerous"] },
      { word: "Roblox", hints: ["A sandbox platform", "Made of many games", "Popular with kids", "User-created content"] },
      { word: "Stumble Guys", hints: ["A party game", "Lots of players race", "Obstacle courses", "Fall Guys competitor"] },
      { word: "Rocket League", hints: ["Soccer with cars", "Boost and aerial tricks", "Three vs three", "Very competitive scene"] },
      { word: "Super Smash Bros", hints: ["Fighting game crossover", "Nintendo characters", "Knock opponents off stage", "Tournament staple"] },
      { word: "Street Fighter", hints: ["Classic fighting game", "Hadouken is iconic", "One-on-one combat", "Combo-heavy gameplay"] },
      { word: "Tekken", hints: ["3D fighting game", "Known for complex inputs", "Long-running series", "King of Iron Fist"] },
      { word: "Hearthstone", hints: ["A digital card game", "Made by Blizzard", "Turn-based strategy", "Collect and build decks"] },
      { word: "StarCraft II", hints: ["A real-time strategy game", "Three factions", "Korean esports legend", "Made by Blizzard"] },
      { word: "Age of Empires", hints: ["A real-time strategy game", "Build civilizations", "Historical settings", "Recently revived"] },
      { word: "Clash Royale", hints: ["A mobile strategy game", "Deploy troops in lanes", "Made by Supercell", "Quick matches"] },
      { word: "Clash of Clans", hints: ["A mobile base-building game", "Raid other players", "Made by Supercell", "Very popular globally"] },
      { word: "Among Us", hints: ["A social deduction game", "Find the impostor", "Tasks on a spaceship", "Blew up during lockdown"] },
      { word: "Fall Guys", hints: ["A party battle royale", "Colorful bean characters", "Obstacle courses", "Last one standing"] },
      { word: "Genshin Impact", hints: ["An open-world RPG", "Gacha mechanics", "Anime art style", "Elemental combat system"] },
      { word: "Mobile Legends", hints: ["A mobile MOBA", "Very popular in Southeast Asia", "Five vs five", "Quick matches"] },
      { word: "Free Fire", hints: ["A mobile battle royale", "Huge in Latin America", "Fast-paced matches", "Made by Garena"] },
      { word: "Brawl Stars", hints: ["A mobile action game", "Three vs three battles", "Made by Supercell", "Cartoon art style"] },
      { word: "Counter-Strike 2", hints: ["Tactical shooter sequel", "Defuse the bomb mode", "Skin economy is huge", "Made by Valve"] },
      { word: "Teamfight Tactics", hints: ["An auto-battler", "Set units on a board", "Part of League universe", "Strategy over reflexes"] },
      { word: "Halo", hints: ["A sci-fi shooter", "Master Chief protagonist", "Xbox exclusive", "Iconic multiplayer"] },
      { word: "Smite", hints: ["A third-person MOBA", "Gods as characters", "Made by Hi-Rez", "Unique camera angle"] },
      { word: "Paladins", hints: ["A hero shooter", "Similar to another game", "Made by Hi-Rez", "Free to play"] },
      { word: "Warzone", hints: ["A battle royale mode", "Part of a shooter franchise", "150 players drop in", "Gulag second chance"] },
      { word: "Dead by Daylight", hints: ["Asymmetric horror game", "One killer vs survivors", "Hide and repair", "Licensed characters"] },
      { word: "League of Legends Wild Rift", hints: ["Mobile version of a MOBA", "Shorter matches", "Made by Riot", "Five vs five"] },
      { word: "Pokémon Unite", hints: ["A MOBA with creatures", "Made by Tencent", "Team battles", "Score points in goals"] },
      { word: "EA Sports FC", hints: ["A football simulation", "Replaced a famous name", "Released yearly", "Ultimate Team mode"] },
      { word: "NBA 2K", hints: ["A basketball simulation", "MyCareer mode", "Released yearly", "Very realistic graphics"] },
      { word: "Gran Turismo", hints: ["A racing simulation", "PlayStation exclusive", "Real car brands", "Very detailed physics"] },
      { word: "F1 Esports", hints: ["Official racing series", "Based on real sport", "Professional drivers compete", "Uses simulation game"] },
      { word: "osu!", hints: ["A rhythm game", "Click circles to the beat", "Very high skill ceiling", "Community-made maps"] },
      { word: "Geometry Dash", hints: ["A rhythm platformer", "One-button gameplay", "Very difficult levels", "Iconic cube character"] },
      { word: "Terraria", hints: ["A 2D sandbox adventure", "Dig and build", "Boss fights included", "Often compared to another game"] },
      { word: "World of Warcraft", hints: ["A massive online RPG", "Raids and dungeons", "Made by Blizzard", "Subscription-based"] },
      { word: "Final Fantasy XIV", hints: ["A story-driven MMORPG", "Critically acclaimed", "Made by Square Enix", "Great community"] },
      { word: "Elden Ring", hints: ["An action RPG", "Open world fantasy", "Made by FromSoftware", "Very challenging"] },
      { word: "Splatoon", hints: ["A colorful shooter", "Paint the map your color", "Nintendo exclusive", "Ink replaces bullets"] },
      { word: "Marvel Rivals", hints: ["A hero team shooter", "Marvel characters", "Six vs six battles", "Recently released"] },
    ],
  },
];

export function randomWord(category: Category): WordEntry {
  return category.words[Math.floor(Math.random() * category.words.length)];
}

export function randomHint(entry: WordEntry): string {
  return entry.hints[Math.floor(Math.random() * entry.hints.length)];
}
